// Copyright (c) 2024, The Endstone Project. (https://endstone.dev) All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#pragma once

#include <vector>

// We do not support compiling under MSVC Debug mode because it sets _ITERATOR_DEBUG_LEVEL
// to a nonzero value, changing the standard library's iterator implementation and resulting
// in an ABI incompatible with the BDS environment, which is built in Release mode.
#ifdef _ITERATOR_DEBUG_LEVEL
static_assert(_ITERATOR_DEBUG_LEVEL == 0,
              "Error: Endstone plugins must be built in Release or RelWithDebInfo mode with MSVC!");
#endif

#include "actor/actor.h"
#include "actor/item.h"
#include "actor/mob.h"
#include "attribute/attribute.h"
#include "attribute/attribute_instance.h"
#include "attribute/attribute_modifier.h"
#include "ban/ban_entry.h"
#include "ban/ban_list.h"
#include "ban/ip_ban_entry.h"
#include "ban/ip_ban_list.h"
#include "ban/player_ban_entry.h"
#include "ban/player_ban_list.h"
#include "block/block.h"
#include "block/block_data.h"
#include "block/block_face.h"
#include "block/block_state.h"
#include "boss/bar_color.h"
#include "boss/bar_flag.h"
#include "boss/bar_style.h"
#include "boss/boss_bar.h"
#include "color_format.h"
#include "command/block_command_sender.h"
#include "command/command.h"
#include "command/command_executor.h"
#include "command/command_map.h"
#include "command/command_sender.h"
#include "command/command_sender_wrapper.h"
#include "command/console_command_sender.h"
#include "command/plugin_command.h"
#include "damage/damage_source.h"
#include "effect/effect_type.h"
#include "enchantments/enchantment.h"
#include "event/actor/actor_damage_event.h"
#include "event/actor/actor_death_event.h"
#include "event/actor/actor_event.h"
#include "event/actor/actor_explode_event.h"
#include "event/actor/actor_knockback_event.h"
#include "event/actor/actor_remove_event.h"
#include "event/actor/actor_spawn_event.h"
#include "event/actor/actor_teleport_event.h"
#include "event/actor/player_death_event.h"
#include "event/block/block_break_event.h"
#include "event/block/block_cook_event.h"
#include "event/block/block_explode_event.h"
#include "event/block/block_event.h"
#include "event/block/block_form_event.h"
#include "event/block/block_from_to_event.h"
#include "event/block/block_grow_event.h"
#include "event/block/block_piston_event.h"
#include "event/block/block_piston_extend_event.h"
#include "event/block/block_piston_retract_event.h"
#include "event/block/block_place_event.h"
#include "event/block/leaves_decay_event.h"
#include "event/cancellable.h"
#include "event/chunk/chunk_event.h"
#include "event/chunk/chunk_load_event.h"
#include "event/chunk/chunk_unload_event.h"
#include "event/event.h"
#include "event/event_handler.h"
#include "event/event_priority.h"
#include "event/handler_list.h"
#include "event/level/dimension_event.h"
#include "event/level/level_event.h"
#include "event/player/player_bed_enter_event.h"
#include "event/player/player_bed_leave_event.h"
#include "event/player/player_chat_event.h"
#include "event/player/player_command_event.h"
#include "event/player/player_dimension_change_event.h"
#include "event/player/player_drop_item_event.h"
#include "event/player/player_emote_event.h"
#include "event/player/player_event.h"
#include "event/player/player_game_mode_change_event.h"
#include "event/player/player_interact_actor_event.h"
#include "event/player/player_interact_event.h"
#include "event/player/player_item_consume_event.h"
#include "event/player/player_item_held_event.h"
#include "event/player/player_join_event.h"
#include "event/player/player_jump_event.h"
#include "event/player/player_kick_event.h"
#include "event/player/player_login_event.h"
#include "event/player/player_move_event.h"
#include "event/player/player_pickup_item_event.h"
#include "event/player/player_portal_event.h"
#include "event/player/player_quit_event.h"
#include "event/player/player_respawn_event.h"
#include "event/player/player_skin_change_event.h"
#include "event/player/player_teleport_event.h"
#include "event/server/broadcast_message_event.h"
#include "event/server/map_initialize_event.h"
#include "event/server/packet_receive_event.h"
#include "event/server/packet_send_event.h"
#include "event/server/plugin_disable_event.h"
#include "event/server/plugin_enable_event.h"
#include "event/server/script_message_event.h"
#include "event/server/server_command_event.h"
#include "event/server/server_event.h"
#include "event/server/server_list_ping_event.h"
#include "event/server/server_load_event.h"
#include "event/weather/thunder_change_event.h"
#include "event/weather/weather_change_event.h"
#include "event/weather/weather_event.h"
#include "form/action_form.h"
#include "form/controls/button.h"
#include "form/controls/dropdown.h"
#include "form/controls/label.h"
#include "form/controls/slider.h"
#include "form/controls/step_slider.h"
#include "form/controls/text_input.h"
#include "form/controls/toggle.h"
#include "form/form.h"
#include "form/message_form.h"
#include "form/modal_form.h"
#include "game_mode.h"
#include "identifier.h"
#include "inventory/equipment_slot.h"
#include "inventory/inventory.h"
#include "inventory/item_factory.h"
#include "inventory/item_stack.h"
#include "inventory/item_type.h"
#include "inventory/meta/book_meta.h"
#include "inventory/meta/crossbow_meta.h"
#include "inventory/meta/item_meta.h"
#include "inventory/meta/map_meta.h"
#include "inventory/meta/writable_book_meta.h"
#include "inventory/player_inventory.h"
#include "inventory/recipe.h"
#include "lang/language.h"
#include "lang/translatable.h"
#include "level/chunk.h"
#include "level/dimension.h"
#include "level/level.h"
#include "level/location.h"
#include "logger.h"
#include "map/map_canvas.h"
#include "map/map_cursor.h"
#include "map/map_renderer.h"
#include "map/map_view.h"
#include "message.h"
#include "nbt/tag.h"
#include "offline_player.h"
#include "permissions/permissible.h"
#include "permissions/permission.h"
#include "permissions/permission_attachment.h"
#include "permissions/permission_attachment_info.h"
#include "permissions/permission_default.h"
#include "permissions/permission_level.h"
#include "player.h"
#include "plugin/plugin.h"
#include "plugin/plugin_description.h"
#include "plugin/plugin_load_order.h"
#include "plugin/plugin_loader.h"
#include "plugin/plugin_manager.h"
#include "plugin/service.h"
#include "plugin/service_manager.h"
#include "plugin/service_priority.h"
#include "potion/potion_type.h"
#include "registry.h"
#include "scheduler/scheduler.h"
#include "scheduler/task.h"
#include "scoreboard/criteria.h"
#include "scoreboard/display_slot.h"
#include "scoreboard/objective.h"
#include "scoreboard/objective_sort_order.h"
#include "scoreboard/render_type.h"
#include "scoreboard/score.h"
#include "scoreboard/score_entry.h"
#include "scoreboard/scoreboard.h"
#include "server.h"
#include "skin.h"
#include "util/color.h"
#include "util/image.h"
#include "util/result.h"
#include "util/socket_address.h"
#include "util/uuid.h"
#include "util/vector.h"
#include "variant.h"
