"""
Classes relating to potion effects.
"""

from endstone import Identifier

__all__ = ["PotionType"]

class PotionType:
    """
    All potion types.
    """

    WATER: Identifier[PotionType] = "minecraft:potion_type:water"
    MUNDANE: Identifier[PotionType] = "minecraft:potion_type:mundane"
    LONG_MUNDANE: Identifier[PotionType] = "minecraft:potion_type:long_mundane"
    THICK: Identifier[PotionType] = "minecraft:potion_type:thick"
    AWKWARD: Identifier[PotionType] = "minecraft:potion_type:awkward"
    NIGHTVISION: Identifier[PotionType] = "minecraft:potion_type:nightvision"
    LONG_NIGHTVISION: Identifier[PotionType] = "minecraft:potion_type:long_nightvision"
    INVISIBILITY: Identifier[PotionType] = "minecraft:potion_type:invisibility"
    LONG_INVISIBILITY: Identifier[PotionType] = "minecraft:potion_type:long_invisibility"
    LEAPING: Identifier[PotionType] = "minecraft:potion_type:leaping"
    LONG_LEAPING: Identifier[PotionType] = "minecraft:potion_type:long_leaping"
    STRONG_LEAPING: Identifier[PotionType] = "minecraft:potion_type:strong_leaping"
    FIRE_RESISTANCE: Identifier[PotionType] = "minecraft:potion_type:fire_resistance"
    LONG_FIRE_RESISTANCE: Identifier[PotionType] = "minecraft:potion_type:long_fire_resistance"
    SWIFTNESS: Identifier[PotionType] = "minecraft:potion_type:swiftness"
    LONG_SWIFTNESS: Identifier[PotionType] = "minecraft:potion_type:long_swiftness"
    STRONG_SWIFTNESS: Identifier[PotionType] = "minecraft:potion_type:strong_swiftness"
    SLOWNESS: Identifier[PotionType] = "minecraft:potion_type:slowness"
    LONG_SLOWNESS: Identifier[PotionType] = "minecraft:potion_type:long_slowness"
    STRONG_SLOWNESS: Identifier[PotionType] = "minecraft:potion_type:strong_slowness"
    WATER_BREATHING: Identifier[PotionType] = "minecraft:potion_type:water_breathing"
    LONG_WATER_BREATHING: Identifier[PotionType] = "minecraft:potion_type:long_water_breathing"
    HEALING: Identifier[PotionType] = "minecraft:potion_type:healing"
    STRONG_HEALING: Identifier[PotionType] = "minecraft:potion_type:strong_healing"
    HARMING: Identifier[PotionType] = "minecraft:potion_type:harming"
    STRONG_HARMING: Identifier[PotionType] = "minecraft:potion_type:strong_harming"
    POISON: Identifier[PotionType] = "minecraft:potion_type:poison"
    LONG_POISON: Identifier[PotionType] = "minecraft:potion_type:long_poison"
    STRONG_POISON: Identifier[PotionType] = "minecraft:potion_type:strong_poison"
    REGENERATION: Identifier[PotionType] = "minecraft:potion_type:regeneration"
    LONG_REGENERATION: Identifier[PotionType] = "minecraft:potion_type:long_regeneration"
    STRONG_REGENERATION: Identifier[PotionType] = "minecraft:potion_type:strong_regeneration"
    STRENGTH: Identifier[PotionType] = "minecraft:potion_type:strength"
    LONG_STRENGTH: Identifier[PotionType] = "minecraft:potion_type:long_strength"
    STRONG_STRENGTH: Identifier[PotionType] = "minecraft:potion_type:strong_strength"
    WEAKNESS: Identifier[PotionType] = "minecraft:potion_type:weakness"
    LONG_WEAKNESS: Identifier[PotionType] = "minecraft:potion_type:long_weakness"
    WITHER: Identifier[PotionType] = "minecraft:potion_type:wither"
    TURTLE_MASTER: Identifier[PotionType] = "minecraft:potion_type:turtle_master"
    LONG_TURTLE_MASTER: Identifier[PotionType] = "minecraft:potion_type:long_turtle_master"
    STRONG_TURTLE_MASTER: Identifier[PotionType] = "minecraft:potion_type:strong_turtle_master"
    SLOW_FALLING: Identifier[PotionType] = "minecraft:potion_type:slow_falling"
    LONG_SLOW_FALLING: Identifier[PotionType] = "minecraft:potion_type:long_slow_falling"
    WIND_CHARGED: Identifier[PotionType] = "minecraft:potion_type:wind_charged"
    WEAVING: Identifier[PotionType] = "minecraft:potion_type:weaving"
    OOZING: Identifier[PotionType] = "minecraft:potion_type:oozing"
    INFESTED: Identifier[PotionType] = "minecraft:potion_type:infested"
