"""
Classes relating to potion effects.
"""

__all__ = ["PotionType"]

class PotionType:
    """
    All potion types.
    """

    WATER = "minecraft:potion_type:water"
    MUNDANE = "minecraft:potion_type:mundane"
    LONG_MUNDANE = "minecraft:potion_type:long_mundane"
    THICK = "minecraft:potion_type:thick"
    AWKWARD = "minecraft:potion_type:awkward"
    NIGHTVISION = "minecraft:potion_type:nightvision"
    LONG_NIGHTVISION = "minecraft:potion_type:long_nightvision"
    INVISIBILITY = "minecraft:potion_type:invisibility"
    LONG_INVISIBILITY = "minecraft:potion_type:long_invisibility"
    LEAPING = "minecraft:potion_type:leaping"
    LONG_LEAPING = "minecraft:potion_type:long_leaping"
    STRONG_LEAPING = "minecraft:potion_type:strong_leaping"
    FIRE_RESISTANCE = "minecraft:potion_type:fire_resistance"
    LONG_FIRE_RESISTANCE = "minecraft:potion_type:long_fire_resistance"
    SWIFTNESS = "minecraft:potion_type:swiftness"
    LONG_SWIFTNESS = "minecraft:potion_type:long_swiftness"
    STRONG_SWIFTNESS = "minecraft:potion_type:strong_swiftness"
    SLOWNESS = "minecraft:potion_type:slowness"
    LONG_SLOWNESS = "minecraft:potion_type:long_slowness"
    STRONG_SLOWNESS = "minecraft:potion_type:strong_slowness"
    WATER_BREATHING = "minecraft:potion_type:water_breathing"
    LONG_WATER_BREATHING = "minecraft:potion_type:long_water_breathing"
    HEALING = "minecraft:potion_type:healing"
    STRONG_HEALING = "minecraft:potion_type:strong_healing"
    HARMING = "minecraft:potion_type:harming"
    STRONG_HARMING = "minecraft:potion_type:strong_harming"
    POISON = "minecraft:potion_type:poison"
    LONG_POISON = "minecraft:potion_type:long_poison"
    STRONG_POISON = "minecraft:potion_type:strong_poison"
    REGENERATION = "minecraft:potion_type:regeneration"
    LONG_REGENERATION = "minecraft:potion_type:long_regeneration"
    STRONG_REGENERATION = "minecraft:potion_type:strong_regeneration"
    STRENGTH = "minecraft:potion_type:strength"
    LONG_STRENGTH = "minecraft:potion_type:long_strength"
    STRONG_STRENGTH = "minecraft:potion_type:strong_strength"
    WEAKNESS = "minecraft:potion_type:weakness"
    LONG_WEAKNESS = "minecraft:potion_type:long_weakness"
    WITHER = "minecraft:potion_type:wither"
    TURTLE_MASTER = "minecraft:potion_type:turtle_master"
    LONG_TURTLE_MASTER = "minecraft:potion_type:long_turtle_master"
    STRONG_TURTLE_MASTER = "minecraft:potion_type:strong_turtle_master"
    SLOW_FALLING = "minecraft:potion_type:slow_falling"
    LONG_SLOW_FALLING = "minecraft:potion_type:long_slow_falling"
    WIND_CHARGED = "minecraft:potion_type:wind_charged"
    WEAVING = "minecraft:potion_type:weaving"
    OOZING = "minecraft:potion_type:oozing"
    INFESTED = "minecraft:potion_type:infested"
