timestamp = 1775122234
version = "1.26.12"

[symbols]
"BlockState::StateListNode::mHead" = 214886704
"Enchant::mEnchants" = 214716536
"getI18n::result" = 213525736
# Actor
"_ZN5Actor10teleportToERK4Vec3biib" = 148626048
# ActorFactory
"_ZN12ActorFactory18createSpawnedActorERK25ActorDefinitionIdentifierP5ActorRK4Vec3RK4Vec2" = 144937536
# BatchedNetworkPeer
"_ZN18BatchedNetworkPeer10sendPacketERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEN11NetworkPeer11ReliabilityE15Compressibility" = 93841184
"_ZN18BatchedNetworkPeer14_receivePacketERNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERKNS0_10shared_ptrINS0_6chrono10time_pointINS9_12steady_clockENS9_8durationIxNS0_5ratioILl1ELl1000000000EEEEEEEEE" = 93841600
# BedrockLog::LogDetails
"_ZN10BedrockLog10LogDetails7_log_vaE9LogAreaIDjPKciiS3_P13__va_list_tag" = 207451168
# BlockDescriptor::ResolveHelper
"_ZN15BlockDescriptor13ResolveHelper7resolveEb" = 177269360
# BlockType
"_ZNK9BlockType14spawnResourcesER11BlockSourceRK8BlockPosRK5BlockR7IRandomRK20ResourceDropsContext" = 175962368
"_ZNK9BlockType25tryGetStateFromLegacyDataEt" = 175954064
# BlockTypeRegistry
"_ZN17BlockTypeRegistry16forEachBlockTypeEN5brstd12function_refIFbRK9BlockTypeES5_EE" = 180600784
# CampfireBlockActor
"_ZN18CampfireBlockActor14_finishCookingER11BlockSourcei" = 183920864
# Certificate
"_ZN11Certificate8validateElbb" = 189713808
# Command
"_ZNK7Command3runERK13CommandOriginR13CommandOutput" = 131041248
# CommandOriginLoader
"_ZN19CommandOriginLoader4loadERK11CompoundTagR11ServerLevel" = 131104896
# CommandRegistry
"_ZN15CommandRegistry13addEnumValuesERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERKNS0_6vectorIS6_NS4_IS6_EEEE" = 131293264
"_ZN15CommandRegistry13registerAliasENSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEES6_" = 131308272
"_ZN15CommandRegistry15registerCommandERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEPKc22CommandPermissionLevel11CommandFlagSC_" = 131298384
"_ZN15CommandRegistry24registerOverloadInternalERNS_9SignatureERNS_8OverloadE" = 131312592
"_ZNK15CommandRegistry14symbolToStringENS_6SymbolE" = 131039536
"_ZNK15CommandRegistry26serializeAvailableCommandsEv" = 131372960
# CommandUtils
"_ZN12CommandUtils12getActorNameERK5Actor" = 131058080
# CraftingDataPacket
"_ZN18CraftingDataPacket18prepareFromRecipesERK7Recipesb" = 108554080
# DedicatedServer
"_ZN15DedicatedServer5startERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERKN7Bedrock19ActivationArgumentsE" = 63083408
# Explosion
"_ZN9Explosion7explodeER7IRandom" = 178306080
# FurnaceBlockActor
"_ZN17FurnaceBlockActor15getBurnDurationERK13ItemStackBasef" = 183684368
# InventoryTransaction
"_ZN20InventoryTransaction23executeWorldInteractionEPvR6PlayerRK15InventoryAction" = 174486352
# Item
"_ZNK4Item12readUserDataER13ItemStackBaseR10IDataInputR20ReadOnlyBinaryStream" = 173985520
# ItemInstance
"_ZN12ItemInstance7fromTagERK11CompoundTag" = 173678560
# ItemRegistry
"_ZNK12ItemRegistry12lookupByNameERiNSt3__117basic_string_viewIcNS1_11char_traitsIcEEEE" = 168705776
# ItemStackBase
"_ZN13ItemStackBase34_loadBlocksForCanPlaceOnCanDestroyERNSt3__16vectorIPK9BlockTypeNS0_9allocatorIS4_EEEERKNS0_12basic_stringIcNS0_11char_traitsIcEENS5_IcEEEE" = 173746480
"_ZN13ItemStackBase4initEiiib" = 173705264
# LeavesBlock
"_ZNK11LeavesBlock10randomTickERN11BlockEvents20BlockRandomTickEventE" = 175372272
# Level
"_ZN5Level4tickEv" = 178486368
# LiquidBlock
"_ZNK11LiquidBlock12_trySpreadToER11BlockSourceRK8BlockPosiS4_h" = 175229872
# MapDataManager
"_ZN14MapDataManager12_loadMapDataERK13ActorUniqueID" = 178190016
# MinecraftCommands
"_ZN17MinecraftCommands14compileCommandERK12HashedStringR13CommandOrigin17CurrentCmdVersionNSt3__18functionIFvRKNS6_12basic_stringIcNS6_11char_traitsIcEENS6_9allocatorIcEEEEEEE" = 130843664
"_ZNK17MinecraftCommands14executeCommandER14CommandContextb" = 130791328
# MinecraftPackets
"_ZN16MinecraftPackets12createPacketE18MinecraftPacketIds" = 111673952
# Mob
"_ZN3Mob9knockbackEP5Actorifffff" = 143692192
# NetworkSystem
"_ZN13NetworkSystem4sendERK17NetworkIdentifierRK6Packet11SubClientId" = 111645152
# Pack
"_ZN4Pack10createPackERK15IPackIOProviderRK16ResourceLocation8PackType10PackOriginR20IPackManifestFactoryN7Bedrock15NonOwnerPointerIK19IContentKeyProviderEEP16PackSourceReportRKN4Core4PathE" = 129338912
# PistonBlockActor
"_ZN16PistonBlockActor4tickER11BlockSource" = 183799408
# Player
"_ZN6Player10teleportToERK4Vec3biib" = 165568784
"_ZN6Player14stopSleepInBedEbb" = 165579696
"_ZN6Player15startSleepInBedERK8BlockPos" = 165575504
"_ZN6Player17completeUsingItemEv" = 165596432
"_ZN6Player4dropERK9ItemStackb" = 165703808
"_ZN6Player4takeER5Actorii" = 165652784
# RakNet::RNS2_Windows_Linux_360
"_ZN6RakNet22RNS2_Windows_Linux_36027Send_Windows_Linux_360NoVDPEiPNS_19RNS2_SendParametersEPKcj" = 190187792
# RakPeerHelper
"_ZN13RakPeerHelper11peerStartupEPN6RakNet16RakPeerInterfaceERK20ConnectionDefinitionNS_11PeerPurposeE" = 111234128
# RepositoryFactory
"_ZNK17RepositoryFactory13createSourcesERK23IResourcePackRepository" = 128521952
# RepositorySources
"_ZN17RepositorySources20initializePackSourceER17PackSourceFactory" = 128924480
# ResourcePackStack
"_ZN17ResourcePackStack11deserializeERNSt3__113basic_istreamIcNS0_11char_traitsIcEEEERKN3gsl8not_nullIN7Bedrock15NonOwnerPointerIK23IResourcePackRepositoryEEEENS0_8optionalINS0_12basic_stringIcS3_NS0_9allocatorIcEEEEEE" = 128390352
# SayCommand
"_ZN10SayCommand12_sendMessageERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEENS0_8optionalIS6_EES8_RK21CommandOriginIdentityR5Level" = 129944304
# ScriptModuleMinecraft::ScriptBlockUtils
"_ZN21ScriptModuleMinecraft16ScriptBlockUtils21createBlockDescriptorENSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS1_8optionalINS1_13unordered_mapIS7_NS1_7variantIJiS7_bEEENS1_4hashIS7_EENS1_8equal_toIS7_EENS5_INS1_4pairIKS7_SB_EEEEEEEE" = 119008640
# ServerInstance
"_ZN14ServerInstance16initializeServerEO27ServerInstanceInitArguments" = 131587088
# ServerNetworkHandler
"_ZN20ServerNetworkHandler15tryToLoadPlayerER12ServerPlayerRK17ConnectionRequestRK24PlayerAuthenticationInfo" = 111440896
"_ZN20ServerNetworkHandler20_validateLoginPacketERK17NetworkIdentifierRK11LoginPacket" = 111369616
"_ZN20ServerNetworkHandler24updateServerAnnouncementEv" = 111356880
"_ZN20ServerNetworkHandler27disconnectClientWithMessageERK17NetworkIdentifier11SubClientIdN10Connection20DisconnectFailReasonERKNSt3__112basic_stringIcNS6_11char_traitsIcEENS6_9allocatorIcEEEENS6_8optionalISC_EEb" = 111304368
"_ZNK20ServerNetworkHandler20_isServerTextEnabledERK15ServerTextEvent" = 111357872
# ServerPlayer
"_ZN12ServerPlayer15changeDimensionE11AutomaticIDI9DimensioniE" = 131698896
# ServerPlayerMovementCorrectionSystem
"_ZN36ServerPlayerMovementCorrectionSystem41_tickServerPlayerMovementCorrectionSystemERK19StrictEntityContextRK36ServerPlayerCurrentMovementComponentRK29UserEntityIdentifierComponentR29ServerPlayerMovementComponent8OptionalIK18PassengerComponentER20StateVectorComponentRK5ViewTIS0_JK22ActorRotationComponent19ActorOwnerComponent20ReplayStateComponentSF_SB_IK21BoatMovementComponentEEE" = 96136160
# ServerScoreboard
"_ZN16ServerScoreboardC2E23CommandSoftEnumRegistryP12LevelStorageN3gsl8not_nullIN7Bedrock15NonOwnerPointerI19GameplayUserManagerEEEE" = 185137488
# UnverifiedCertificate
"_ZN21UnverifiedCertificate10fromStringERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE" = 189708016
# WeatherManager
"_ZN14WeatherManager13updateWeatherEfifi" = 177891696
