"""
Classes relating to the NBT data format.
"""

import collections
import typing

__all__ = [
    "ByteArrayTag",
    "ByteTag",
    "CompoundTag",
    "DoubleTag",
    "FloatTag",
    "IntArrayTag",
    "IntTag",
    "ListTag",
    "LongTag",
    "ShortTag",
    "StringTag",
    "Tag",
]

class Tag: ...

class ByteTag(Tag):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, value: int) -> None: ...
    @property
    def value(self) -> int: ...
    @typing.overload
    def __eq__(self, arg0: ByteTag) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: int) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: int) -> bool: ...
    @typing.overload
    def __ne__(self, arg0: ByteTag) -> bool: ...
    @typing.overload
    def __ne__(self, arg0: int) -> bool: ...
    @typing.overload
    def __ne__(self, arg0: int) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __int__(self) -> int: ...

class ShortTag(Tag):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, value: int) -> None: ...
    @property
    def value(self) -> int: ...
    @typing.overload
    def __eq__(self, arg0: ShortTag) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: int) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: int) -> bool: ...
    @typing.overload
    def __ne__(self, arg0: ShortTag) -> bool: ...
    @typing.overload
    def __ne__(self, arg0: int) -> bool: ...
    @typing.overload
    def __ne__(self, arg0: int) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __int__(self) -> int: ...

class IntTag(Tag):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, value: int) -> None: ...
    @property
    def value(self) -> int: ...
    @typing.overload
    def __eq__(self, arg0: IntTag) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: int) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: int) -> bool: ...
    @typing.overload
    def __ne__(self, arg0: IntTag) -> bool: ...
    @typing.overload
    def __ne__(self, arg0: int) -> bool: ...
    @typing.overload
    def __ne__(self, arg0: int) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __int__(self) -> int: ...

class LongTag(Tag):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, value: int) -> None: ...
    @property
    def value(self) -> int: ...
    @typing.overload
    def __eq__(self, arg0: LongTag) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: int) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: int) -> bool: ...
    @typing.overload
    def __ne__(self, arg0: LongTag) -> bool: ...
    @typing.overload
    def __ne__(self, arg0: int) -> bool: ...
    @typing.overload
    def __ne__(self, arg0: int) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __int__(self) -> int: ...

class FloatTag(Tag):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, value: float) -> None: ...
    @property
    def value(self) -> float: ...
    @typing.overload
    def __eq__(self, arg0: FloatTag) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: float) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: float) -> bool: ...
    @typing.overload
    def __ne__(self, arg0: FloatTag) -> bool: ...
    @typing.overload
    def __ne__(self, arg0: float) -> bool: ...
    @typing.overload
    def __ne__(self, arg0: float) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __float__(self) -> float: ...

class DoubleTag(Tag):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, value: float) -> None: ...
    @property
    def value(self) -> float: ...
    @typing.overload
    def __eq__(self, arg0: DoubleTag) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: float) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: float) -> bool: ...
    @typing.overload
    def __ne__(self, arg0: DoubleTag) -> bool: ...
    @typing.overload
    def __ne__(self, arg0: float) -> bool: ...
    @typing.overload
    def __ne__(self, arg0: float) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __float__(self) -> float: ...

class ByteArrayTag(Tag):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, iterable: collections.abc.Iterable) -> None: ...
    @typing.overload
    def __init__(self, buffer: collections.abc.Buffer) -> None: ...
    def __buffer__(self, flags) -> None:
        """
        Return a buffer object that exposes the underlying memory of the object.
        """
        ...
    def __release_buffer__(self, buffer) -> None:
        """
        Release the buffer object that exposes the underlying memory of the object.
        """
        ...
    def clear(self) -> None: ...
    def append(self, value: int) -> None: ...
    def extend(self, iterable: collections.abc.Iterable) -> None: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __getitem__(self, arg0: int) -> int: ...
    def __setitem__(self, arg0: int, arg1: int) -> None: ...
    def __iter__(self) -> collections.abc.Iterator[int]: ...
    @typing.overload
    def __eq__(self, arg0: ByteArrayTag) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: list[int]) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: list[int]) -> bool: ...
    @typing.overload
    def __ne__(self, arg0: ByteArrayTag) -> bool: ...
    @typing.overload
    def __ne__(self, arg0: list[int]) -> bool: ...
    @typing.overload
    def __ne__(self, arg0: list[int]) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __bytes__(self) -> bytes: ...

class StringTag(Tag):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, value: str) -> None: ...
    @property
    def value(self) -> str: ...
    @typing.overload
    def __eq__(self, arg0: StringTag) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: str) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: str) -> bool: ...
    @typing.overload
    def __ne__(self, arg0: StringTag) -> bool: ...
    @typing.overload
    def __ne__(self, arg0: str) -> bool: ...
    @typing.overload
    def __ne__(self, arg0: str) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class IntArrayTag(Tag):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, iterable: collections.abc.Iterable) -> None: ...
    def clear(self) -> None: ...
    def append(self, value: int) -> None: ...
    def extend(self, iterable: collections.abc.Iterable) -> None: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __getitem__(self, arg0: int) -> int: ...
    def __setitem__(self, arg0: int, arg1: int) -> None: ...
    def __iter__(self) -> collections.abc.Iterator[int]: ...
    @typing.overload
    def __eq__(self, arg0: IntArrayTag) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: list[int]) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: list[int]) -> bool: ...
    @typing.overload
    def __ne__(self, arg0: IntArrayTag) -> bool: ...
    @typing.overload
    def __ne__(self, arg0: list[int]) -> bool: ...
    @typing.overload
    def __ne__(self, arg0: list[int]) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class ListTag(Tag):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, iterable: collections.abc.Iterable) -> None: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __getitem__(self, arg0: int) -> Tag: ...
    def __setitem__(self, arg0: int, arg1: Tag) -> None: ...
    def __delitem__(self, arg0: int) -> None: ...
    def __iter__(self) -> collections.abc.Iterator[Tag]: ...
    def clear(self) -> None: ...
    def append(self, tag: Tag) -> None: ...
    def extend(self, iterable: collections.abc.Iterable) -> None: ...
    def pop(self, index: int = -1) -> Tag: ...
    def to_list(self) -> list: ...
    def size(self) -> int: ...
    def empty(self) -> bool: ...
    def __eq__(self, arg0: ListTag) -> bool: ...
    def __ne__(self, arg0: ListTag) -> bool: ...

class CompoundTag(Tag):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, mapping: dict) -> None: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __contains__(self, key: str) -> bool: ...
    def __getitem__(self, arg0: str) -> Tag: ...
    def __setitem__(self, arg0: str, arg1: Tag) -> None: ...
    def setdefault(self, key: str, default: Tag) -> Tag: ...
    def clear(self) -> None: ...
    @typing.overload
    def pop(self, key: str) -> Tag: ...
    @typing.overload
    def pop(self, key: str, default: object = None) -> object: ...
    def __iter__(self) -> collections.abc.Iterator[str]: ...
    def keys(self) -> collections.abc.Iterator[str]: ...
    def values(self) -> collections.abc.Iterator[Tag]: ...
    def items(self) -> collections.abc.Iterator[tuple[str, Tag]]: ...
    def __eq__(self, arg0: CompoundTag) -> bool: ...
    def __ne__(self, arg0: CompoundTag) -> bool: ...
    def to_dict(self) -> dict: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
