"""
Classes relating to the NBT data format.
"""

import collections
import typing

__all__ = [
    "ByteArrayTag",
    "ByteTag",
    "CompoundTag",
    "DoubleTag",
    "FloatTag",
    "IntArrayTag",
    "IntTag",
    "ListTag",
    "LongTag",
    "ShortTag",
    "StringTag",
    "Tag",
    "load",
]

class Tag: ...

class ByteTag(Tag):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, value: int) -> None: ...
    @property
    def value(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __int__(self) -> int: ...
    def dump(
        self, name: str | None = None, byte_order: typing.Literal["little", "big"] = "little", network: bool = False
    ) -> bytes:
        """
        Serialize this tag to binary NBT format.

        Args:
            name: Optional root tag name. If None, an empty name is used.
            byte_order: Byte order for encoding, either ``'little'`` (Bedrock) or ``'big'`` (Java).
            network: If True, use Bedrock network varint encoding for lengths and Int/Long values.

        Returns:
            bytes: The binary NBT data.
        """
        ...

class ShortTag(Tag):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, value: int) -> None: ...
    @property
    def value(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __int__(self) -> int: ...
    def dump(
        self, name: str | None = None, byte_order: typing.Literal["little", "big"] = "little", network: bool = False
    ) -> bytes:
        """
        Serialize this tag to binary NBT format.

        Args:
            name: Optional root tag name. If None, an empty name is used.
            byte_order: Byte order for encoding, either ``'little'`` (Bedrock) or ``'big'`` (Java).
            network: If True, use Bedrock network varint encoding for lengths and Int/Long values.

        Returns:
            bytes: The binary NBT data.
        """
        ...

class IntTag(Tag):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, value: int) -> None: ...
    @property
    def value(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __int__(self) -> int: ...
    def dump(
        self, name: str | None = None, byte_order: typing.Literal["little", "big"] = "little", network: bool = False
    ) -> bytes:
        """
        Serialize this tag to binary NBT format.

        Args:
            name: Optional root tag name. If None, an empty name is used.
            byte_order: Byte order for encoding, either ``'little'`` (Bedrock) or ``'big'`` (Java).
            network: If True, use Bedrock network varint encoding for lengths and Int/Long values.

        Returns:
            bytes: The binary NBT data.
        """
        ...

class LongTag(Tag):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, value: int) -> None: ...
    @property
    def value(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __int__(self) -> int: ...
    def dump(
        self, name: str | None = None, byte_order: typing.Literal["little", "big"] = "little", network: bool = False
    ) -> bytes:
        """
        Serialize this tag to binary NBT format.

        Args:
            name: Optional root tag name. If None, an empty name is used.
            byte_order: Byte order for encoding, either ``'little'`` (Bedrock) or ``'big'`` (Java).
            network: If True, use Bedrock network varint encoding for lengths and Int/Long values.

        Returns:
            bytes: The binary NBT data.
        """
        ...

class FloatTag(Tag):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, value: float) -> None: ...
    @property
    def value(self) -> float: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __float__(self) -> float: ...
    def dump(
        self, name: str | None = None, byte_order: typing.Literal["little", "big"] = "little", network: bool = False
    ) -> bytes:
        """
        Serialize this tag to binary NBT format.

        Args:
            name: Optional root tag name. If None, an empty name is used.
            byte_order: Byte order for encoding, either ``'little'`` (Bedrock) or ``'big'`` (Java).
            network: If True, use Bedrock network varint encoding for lengths and Int/Long values.

        Returns:
            bytes: The binary NBT data.
        """
        ...

class DoubleTag(Tag):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, value: float) -> None: ...
    @property
    def value(self) -> float: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __float__(self) -> float: ...
    def dump(
        self, name: str | None = None, byte_order: typing.Literal["little", "big"] = "little", network: bool = False
    ) -> bytes:
        """
        Serialize this tag to binary NBT format.

        Args:
            name: Optional root tag name. If None, an empty name is used.
            byte_order: Byte order for encoding, either ``'little'`` (Bedrock) or ``'big'`` (Java).
            network: If True, use Bedrock network varint encoding for lengths and Int/Long values.

        Returns:
            bytes: The binary NBT data.
        """
        ...

class ByteArrayTag(Tag):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, iterable: collections.abc.Iterable) -> None: ...
    @typing.overload
    def __init__(self, buffer: collections.abc.Buffer) -> None: ...
    def __buffer__(self, flags) -> None:
        """
        Return a buffer object that exposes the underlying memory of the object.
        """
        ...
    def __release_buffer__(self, buffer) -> None:
        """
        Release the buffer object that exposes the underlying memory of the object.
        """
        ...
    def clear(self) -> None: ...
    def append(self, value: int) -> None: ...
    def extend(self, iterable: collections.abc.Iterable) -> None: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __getitem__(self, arg0: int) -> int: ...
    def __setitem__(self, arg0: int, arg1: int) -> None: ...
    def __iter__(self) -> collections.abc.Iterator[int]: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __bytes__(self) -> bytes: ...
    def dump(
        self, name: str | None = None, byte_order: typing.Literal["little", "big"] = "little", network: bool = False
    ) -> bytes:
        """
        Serialize this tag to binary NBT format.

        Args:
            name: Optional root tag name. If None, an empty name is used.
            byte_order: Byte order for encoding, either ``'little'`` (Bedrock) or ``'big'`` (Java).
            network: If True, use Bedrock network varint encoding for lengths and Int/Long values.

        Returns:
            bytes: The binary NBT data.
        """
        ...

class StringTag(Tag):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, value: str) -> None: ...
    @property
    def value(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def dump(
        self, name: str | None = None, byte_order: typing.Literal["little", "big"] = "little", network: bool = False
    ) -> bytes:
        """
        Serialize this tag to binary NBT format.

        Args:
            name: Optional root tag name. If None, an empty name is used.
            byte_order: Byte order for encoding, either ``'little'`` (Bedrock) or ``'big'`` (Java).
            network: If True, use Bedrock network varint encoding for lengths and Int/Long values.

        Returns:
            bytes: The binary NBT data.
        """
        ...

class IntArrayTag(Tag):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, iterable: collections.abc.Iterable) -> None: ...
    def clear(self) -> None: ...
    def append(self, value: int) -> None: ...
    def extend(self, iterable: collections.abc.Iterable) -> None: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __getitem__(self, arg0: int) -> int: ...
    def __setitem__(self, arg0: int, arg1: int) -> None: ...
    def __iter__(self) -> collections.abc.Iterator[int]: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def dump(
        self, name: str | None = None, byte_order: typing.Literal["little", "big"] = "little", network: bool = False
    ) -> bytes:
        """
        Serialize this tag to binary NBT format.

        Args:
            name: Optional root tag name. If None, an empty name is used.
            byte_order: Byte order for encoding, either ``'little'`` (Bedrock) or ``'big'`` (Java).
            network: If True, use Bedrock network varint encoding for lengths and Int/Long values.

        Returns:
            bytes: The binary NBT data.
        """
        ...

class ListTag(Tag):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, iterable: collections.abc.Iterable) -> None: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __getitem__(self, arg0: int) -> Tag: ...
    def __setitem__(self, arg0: int, arg1: Tag) -> None: ...
    def __delitem__(self, arg0: int) -> None: ...
    def __iter__(self) -> collections.abc.Iterator[Tag]: ...
    def clear(self) -> None: ...
    def append(self, tag: Tag) -> None: ...
    def extend(self, iterable: collections.abc.Iterable) -> None: ...
    def pop(self, index: int = -1) -> Tag: ...
    def to_list(self) -> list: ...
    def size(self) -> int: ...
    def empty(self) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def dump(
        self, name: str | None = None, byte_order: typing.Literal["little", "big"] = "little", network: bool = False
    ) -> bytes:
        """
        Serialize this tag to binary NBT format.

        Args:
            name: Optional root tag name. If None, an empty name is used.
            byte_order: Byte order for encoding, either ``'little'`` (Bedrock) or ``'big'`` (Java).
            network: If True, use Bedrock network varint encoding for lengths and Int/Long values.

        Returns:
            bytes: The binary NBT data.
        """
        ...

class CompoundTag(Tag):
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, mapping: dict) -> None: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __contains__(self, key: str) -> bool: ...
    def __getitem__(self, arg0: str) -> Tag: ...
    def __setitem__(self, arg0: str, arg1: Tag) -> None: ...
    def setdefault(self, key: str, default: Tag) -> Tag: ...
    def clear(self) -> None: ...
    @typing.overload
    def pop(self, key: str) -> Tag: ...
    @typing.overload
    def pop(self, key: str, default: object = None) -> object: ...
    def __iter__(self) -> collections.abc.Iterator[str]: ...
    def keys(self) -> collections.abc.Iterator[str]: ...
    def values(self) -> collections.abc.Iterator[Tag]: ...
    def items(self) -> collections.abc.Iterator[tuple[str, Tag]]: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def to_dict(self) -> dict: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def dump(
        self, name: str | None = None, byte_order: typing.Literal["little", "big"] = "little", network: bool = False
    ) -> bytes:
        """
        Serialize this tag to binary NBT format.

        Args:
            name: Optional root tag name. If None, an empty name is used.
            byte_order: Byte order for encoding, either ``'little'`` (Bedrock) or ``'big'`` (Java).
            network: If True, use Bedrock network varint encoding for lengths and Int/Long values.

        Returns:
            bytes: The binary NBT data.
        """
        ...

def load(data: bytes, byte_order: typing.Literal["little", "big"] = "little", network: bool = False) -> tuple[Tag, str]:
    """
    Deserialize binary NBT data into a tag.

    Args:
        data: Binary NBT data (bytes).
        byte_order: Byte order of the binary data, either ``'little'`` (Bedrock) or ``'big'`` (Java).
        network: If True, expect Bedrock network varint encoding.

    Returns:
        tuple[Tag, str]: A tuple of (tag, name) where name is the root tag name.
    """
    ...
