from endstone import Logger, Server

class PluginLoader: ...

class Plugin:
    def __init__(self) -> None: ...
    def on_disable(self) -> None: ...
    def on_enable(self) -> None: ...
    def on_load(self) -> None: ...
    @property
    def enabled(self) -> bool: ...
    @property
    def logger(self) -> Logger: ...
    @property
    def plugin_loader(self) -> PluginLoader: ...
    @property
    def server(self) -> Server: ...
