// Generated by scripts/dump_symbols.py for BDS 1.26.45 (linux). DO NOT EDIT.
// clang-format off
// NOLINTBEGIN

#pragma once

#include <array>
#include <cstddef>
#include <string_view>
#include <utility>

namespace endstone::runtime {

static constexpr std::array<std::pair<std::string_view, std::size_t>, 61> symbols = {{
    {"BlockState::StateListNode::mHead", 245466592},
    {"Enchant::mEnchants", 245292608},
    {"getI18n::result", 244109040},
    // Actor
    {"_ZN5Actor10teleportToERK4Vec3biib", 180243264},
    // ActorFactory
    {"_ZN12ActorFactory18createSpawnedActorERK25ActorDefinitionIdentifierP5ActorRK4Vec3RK4Vec2", 178029744},
    // BatchedNetworkPeer
    {"_ZN18BatchedNetworkPeer10sendPacketERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEN11NetworkPeer11ReliabilityE15Compressibility", 115687520},
    {"_ZN18BatchedNetworkPeer14_receivePacketERNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERKNS0_10shared_ptrINS0_6chrono10time_pointINS9_12steady_clockENS9_8durationIxNS0_5ratioILl1ELl1000000000EEEEEEEEE", 115687936},
    // BedrockLog::LogDetails
    {"_ZN10BedrockLog10LogDetails7_log_vaE9LogAreaIDjPKciiS3_P13__va_list_tag", 237068352},
    // BlockDescriptor::ResolveHelper
    {"_ZN15BlockDescriptor13ResolveHelper7resolveEb", 200713328},
    // BlockType
    {"_ZNK9BlockType14spawnResourcesER11BlockSourceRK8BlockPosRK5BlockR7IRandomRK20ResourceDropsContextPK5Actor", 199390176},
    {"_ZNK9BlockType25tryGetStateFromLegacyDataEt", 199381824},
    // BlockTypeRegistry
    {"_ZNK17BlockTypeRegistry16forEachBlockTypeEN5brstd12function_refIFbRK9BlockTypeES5_EE", 203855488},
    // CampfireBlockActor
    {"_ZN18CampfireBlockActor14_finishCookingER11BlockSourcei", 207807344},
    // Command
    {"_ZNK7Command3runERK13CommandOriginR13CommandOutput", 160429376},
    // CommandOriginLoader
    {"_ZN19CommandOriginLoader4loadERK11CompoundTagR11ServerLevel", 160489696},
    // CommandRegistry
    {"_ZN15CommandRegistry13addEnumValuesERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERKNS0_6vectorIS6_NS4_IS6_EEEE", 159954176},
    {"_ZN15CommandRegistry13registerAliasENSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEES6_", 159970592},
    {"_ZN15CommandRegistry15registerCommandERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEPKc22CommandPermissionLevel11CommandFlagSC_", 159960464},
    {"_ZN15CommandRegistry24registerOverloadInternalERNS_9SignatureERNS_8OverloadE", 159974464},
    {"_ZNK15CommandRegistry14symbolToStringENS_6SymbolE", 159851120},
    {"_ZNK15CommandRegistry26serializeAvailableCommandsEv", 160038160},
    // CommandUtils
    {"_ZN12CommandUtils12getActorNameERK5Actor", 159773600},
    // CraftingDataPacketPayload
    {"_ZN25CraftingDataPacketPayload11fromRecipesERK7Recipesb", 134784784},
    // DedicatedServer
    {"_ZN15DedicatedServer5startERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERKN7Bedrock19ActivationArgumentsE", 71549824},
    // Explosion
    {"_ZN9Explosion7explodeER7IRandom", 202092368},
    // FurnaceBlockActor
    {"_ZN17FurnaceBlockActor15getBurnDurationERK13ItemStackBasef", 207576016},
    // InventoryTransaction
    {"_ZN20InventoryTransaction23executeWorldInteractionEPvR6PlayerRK15InventoryAction", 197768464},
    // Item
    {"_ZNK4Item12readUserDataER13ItemStackBaseR10IDataInputR20ReadOnlyBinaryStream", 197129008},
    // ItemInstance
    {"_ZN12ItemInstance7fromTagERK11CompoundTag", 196790944},
    // ItemRegistry
    {"_ZNK12ItemRegistry12lookupByNameERiNSt3__117basic_string_viewIcNS1_11char_traitsIcEEEE", 191712880},
    // ItemStackBase
    {"_ZN13ItemStackBase34_loadBlocksForCanPlaceOnCanDestroyERNSt3__16vectorIPK9BlockTypeNS0_9allocatorIS4_EEEERKNS0_12basic_stringIcNS0_11char_traitsIcEENS5_IcEEEE", 196857552},
    {"_ZN13ItemStackBase8_setItemEib", 196816848},
    // LeavesBlock
    {"_ZN11LeavesBlock10randomTickERN11BlockEvents20BlockRandomTickEventE", 199007632},
    // Level
    {"_ZN5Level4tickEv", 201847072},
    // LiquidBlock
    {"_ZNK11LiquidBlock12_trySpreadToER11BlockSourceRK8BlockPosiS4_h", 198738160},
    // MapDataManager
    {"_ZN14MapDataManager15getMapSavedDataE13ActorUniqueID", 201899600},
    // MinecraftCommands
    {"_ZN17MinecraftCommands14compileCommandERK12HashedStringR13CommandOrigin17CurrentCmdVersionNSt3__18functionIFvRKNS6_12basic_stringIcNS6_11char_traitsIcEENS6_9allocatorIcEEEEEEE", 160145888},
    {"_ZNK17MinecraftCommands14executeCommandER14CommandContextb", 160092384},
    // MinecraftPackets
    {"_ZN16MinecraftPackets12createPacketE18MinecraftPacketIds", 140174016},
    // Mob
    {"_ZN3Mob9knockbackEP5ActorfffRK19KnockbackParameters", 191348496},
    // NetworkSystem
    {"_ZN13NetworkSystem4sendERK17NetworkIdentifierRK6Packet11SubClientId", 140169552},
    // PistonBlockActor
    {"_ZN16PistonBlockActor4tickER11BlockSource", 207193472},
    // Player
    {"_ZN6Player10teleportToERK4Vec3biib", 188136016},
    {"_ZN6Player14stopSleepInBedEbb", 188147104},
    {"_ZN6Player15startSleepInBedERK8BlockPosbf", 188142832},
    {"_ZN6Player17completeUsingItemEv", 188166480},
    {"_ZN6Player4dropERK9ItemStackb", 188278672},
    {"_ZN6Player4takeER5Actorii", 188225936},
    // RakNet::RNS2_Windows_Linux_360
    {"_ZN6RakNet22RNS2_Windows_Linux_36027Send_Windows_Linux_360NoVDPEiPNS_19RNS2_SendParametersEPKcj", 214784976},
    // RakPeerHelper
    {"_ZN13RakPeerHelper11peerStartupEPN6RakNet16RakPeerInterfaceERK20ConnectionDefinitionNS_11PeerPurposeE", 140304592},
    // RepositoryFactory
    {"_ZNK17RepositoryFactory13createSourcesERK23IResourcePackRepository", 157556384},
    // SayCommand
    {"_ZN10SayCommand12_sendMessageERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERKNS0_8optionalIS6_EES8_RK21CommandOriginIdentityR5Level", 158350016},
    // ScriptModuleMinecraft::ScriptBlockUtils
    {"_ZN21ScriptModuleMinecraft16ScriptBlockUtils21createBlockDescriptorENSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS1_8optionalINS1_13unordered_mapIS7_NS1_7variantIJiS7_bEEENS1_4hashIS7_EENS1_8equal_toIS7_EENS5_INS1_4pairIKS7_SB_EEEEEEEE", 140882880},
    // ServerInstance
    {"_ZN14ServerInstance16initializeServerEO27ServerInstanceInitArguments", 161656368},
    // ServerNetworkHandler
    {"_ZN20ServerNetworkHandler15tryToLoadPlayerER12ServerPlayerRK17ConnectionRequestRK24PlayerAuthenticationInfo", 139460432},
    {"_ZN20ServerNetworkHandler20_validateLoginPacketERK17NetworkIdentifierRK11LoginPacket", 139378720},
    {"_ZN20ServerNetworkHandler24updateServerAnnouncementEv", 139363664},
    {"_ZN20ServerNetworkHandler27disconnectClientWithMessageERK17NetworkIdentifier11SubClientIdN10Connection20DisconnectFailReasonERKNSt3__112basic_stringIcNS6_11char_traitsIcEENS6_9allocatorIcEEEENS6_8optionalISC_EE", 139300176},
    // ServerPlayer
    {"_ZN12ServerPlayer15changeDimensionE13DimensionType", 160364032},
    // ServerScoreboard
    {"_ZN16ServerScoreboardC2E23CommandSoftEnumRegistryP12LevelStorageN3gsl8not_nullIN7Bedrock15NonOwnerPointerI19GameplayUserManagerEEEE", 209065792},
    // WeatherManager
    {"_ZN14WeatherManager13updateWeatherEfifi", 201401104},
}};

}  // namespace endstone::runtime

// NOLINTEND
// clang-format on
