// Generated by scripts/dump_symbols.py for BDS 1.26.51 (linux). DO NOT EDIT.
// clang-format off
// NOLINTBEGIN

#pragma once

#include <array>
#include <cstddef>
#include <string_view>
#include <utility>

namespace endstone::runtime {

static constexpr std::array<std::pair<std::string_view, std::size_t>, 66> symbols = {{
    {"BlockState::StateListNode::mHead", 257927632},
    {"Enchant::mEnchants", 257764288},
    {"getI18n::result", 256810296},
    // Actor
    {"_ZN5Actor10teleportToERK4Vec3biib", 187568000},
    // ActorFactory
    {"_ZN12ActorFactory18createSpawnedActorERK25ActorDefinitionIdentifierP5ActorRK4Vec3RK4Vec2", 183845440},
    // BatchedNetworkPeer
    {"_ZN18BatchedNetworkPeer10sendPacketERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEN11NetworkPeer11ReliabilityE15Compressibility", 145216864},
    {"_ZN18BatchedNetworkPeer14_receivePacketERNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERKNS0_10shared_ptrINS0_6chrono10time_pointINS9_12steady_clockENS9_8durationIxNS0_5ratioILl1ELl1000000000EEEEEEEEE", 145217280},
    // BedrockLog::LogDetails
    {"_ZN10BedrockLog10LogDetails7_log_vaE9LogAreaIDjPKciiS3_P13__va_list_tag", 249277264},
    // BlockDescriptor::ResolveHelper
    {"_ZN15BlockDescriptor13ResolveHelper7resolveEb", 207533120},
    // BlockType
    {"_ZNK9BlockType14spawnResourcesER11BlockSourceRK8BlockPosRK5BlockR7IRandomRK20ResourceDropsContextPK5Actor", 207398176},
    {"_ZNK9BlockType25tryGetStateFromLegacyDataEt", 207389872},
    // BlockTypeRegistry
    {"_ZNK17BlockTypeRegistry16forEachBlockTypeEN5brstd12function_refIFbRK9BlockTypeES5_EE", 213117648},
    // CampfireBlockActor
    {"_ZN18CampfireBlockActor14_finishCookingER11BlockSourcei", 216525872},
    // Command
    {"_ZNK7Command3runERK13CommandOriginR13CommandOutput", 164685552},
    // CommandOriginLoader
    {"_ZN19CommandOriginLoader4loadERK11CompoundTagR11ServerLevel", 164751424},
    // CommandRegistry
    {"_ZN15CommandRegistry13addEnumValuesERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERKNS0_6vectorIS6_NS4_IS6_EEEE", 164216320},
    {"_ZN15CommandRegistry13registerAliasENSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEES6_", 164231792},
    {"_ZN15CommandRegistry15registerCommandERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEPKc22CommandPermissionLevel11CommandFlagSC_", 164222192},
    {"_ZN15CommandRegistry24registerOverloadInternalERNS_9SignatureERNS_8OverloadE", 164235936},
    {"_ZNK15CommandRegistry14symbolToStringENS_6SymbolE", 164119840},
    {"_ZNK15CommandRegistry26serializeAvailableCommandsEv", 164297952},
    // CommandUtils
    {"_ZN12CommandUtils12getActorNameERK5Actor", 164347680},
    // CraftingDataPacketPayload
    {"_ZN25CraftingDataPacketPayload11fromRecipesERK7Recipesb", 140476752},
    // DedicatedServer
    {"_ZN15DedicatedServer5startERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERKN7Bedrock19ActivationArgumentsE", 75250480},
    // Explosion
    {"_ZN9Explosion7explodeER7IRandom", 210159264},
    // FurnaceBlockActor
    {"_ZN17FurnaceBlockActor15getBurnDurationERK13ItemStackBasef", 216337968},
    // InventoryTransaction
    {"_ZN20InventoryTransaction23executeWorldInteractionEPvR6PlayerRK15InventoryAction", 205811088},
    // Item
    {"_ZNK4Item12readUserDataER13ItemStackBaseR10IDataInputR20ReadOnlyBinaryStream", 205116320},
    // ItemInstance
    {"_ZN12ItemInstance7fromTagERK11CompoundTag", 204797424},
    // ItemRegistry
    {"_ZNK12ItemRegistry12lookupByNameERiNSt3__117basic_string_viewIcNS1_11char_traitsIcEEEE", 210812480},
    // ItemStackBase
    {"_ZN13ItemStackBase34_loadBlocksForCanPlaceOnCanDestroyERNSt3__16vectorIPK9BlockTypeNS0_9allocatorIS4_EEEERKNS0_12basic_stringIcNS0_11char_traitsIcEENS5_IcEEEE", 204862752},
    {"_ZN13ItemStackBase8_setItemEib", 204823536},
    // LeavesBlock
    {"_ZN11LeavesBlock10randomTickERN11BlockEvents20BlockRandomTickEventE", 207060560},
    // Level
    {"_ZN5Level4tickEv", 210334432},
    // LiquidBlock
    {"_ZNK11LiquidBlock12_trySpreadToER11BlockSourceRK8BlockPosiS4_h", 206815744},
    // MapDataManager
    {"_ZN14MapDataManager15getMapSavedDataE13ActorUniqueID", 210021440},
    // MinecraftCommands
    {"_ZN17MinecraftCommands14compileCommandERK12HashedStringR13CommandOrigin17CurrentCmdVersionNSt3__18functionIFvRKNS6_12basic_stringIcNS6_11char_traitsIcEENS6_9allocatorIcEEEEEEE", 164402000},
    {"_ZNK17MinecraftCommands14executeCommandER14CommandContextb", 164352576},
    // MinecraftPackets
    {"_ZN16MinecraftPackets12createPacketE18MinecraftPacketIds", 144682608},
    // Mob
    {"_ZN3Mob9knockbackEP5ActorfffRK19KnockbackParameters", 199752288},
    // NetherNet::LanThreadManager
    {"_ZN9NetherNet16LanThreadManager24SendLanBroadcastResponseERKN6webrtc13SocketAddressENS_9NetworkIDENSt3__112basic_stringIcNS6_11char_traitsIcEENS6_9allocatorIcEEEE", 222749872},
    // NetherNet::SimpleNetworkInterfaceImpl
    {"_ZN9NetherNet26SimpleNetworkInterfaceImpl27ReceiveFromSignalingChannelENS_9NetworkIDENSt3__117basic_string_viewIcNS2_11char_traitsIcEEEENS_18SignalingChannelIdE", 222785168},
    // NetherNet::TransportFactoryImpl
    {"_ZN9NetherNet20TransportFactoryImpl24createTransportInterfaceERKNS_9NetworkIDERKNS_22TransportConfigurationEPNS_37INetherNetTransportInterfaceCallbacksE", 223038384},
    // NetworkSystem
    {"_ZN13NetworkSystem4sendERK17NetworkIdentifierRK6Packet11SubClientId", 144723008},
    // PistonBlockActor
    {"_ZN16PistonBlockActor4tickER11BlockSource", 216115504},
    // Player
    {"_ZN6Player10teleportToERK4Vec3biib", 196297232},
    {"_ZN6Player14stopSleepInBedEbb", 196308992},
    {"_ZN6Player15startSleepInBedERK8BlockPosbf", 196304128},
    {"_ZN6Player17completeUsingItemEv", 196328640},
    {"_ZN6Player4dropERK9ItemStackb", 196440144},
    {"_ZN6Player4takeER5Actorii", 196389024},
    // RakNet::RNS2_Windows_Linux_360
    {"_ZN6RakNet22RNS2_Windows_Linux_36027Send_Windows_Linux_360NoVDPEiPNS_19RNS2_SendParametersEPKcj", 224306768},
    // RakPeerHelper
    {"_ZN13RakPeerHelper11peerStartupEPN6RakNet16RakPeerInterfaceERK20ConnectionDefinitionNS_11PeerPurposeE", 144810336},
    // RepositoryFactory
    {"_ZNK17RepositoryFactory13createSourcesERK23IResourcePackRepository", 161627424},
    // SayCommand
    {"_ZN10SayCommand12_sendMessageERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERKNS0_8optionalIS6_EES8_RK21CommandOriginIdentityR5Level", 163338480},
    // ScriptModuleMinecraft::ScriptBlockUtils
    {"_ZN21ScriptModuleMinecraft16ScriptBlockUtils21createBlockDescriptorENSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS1_8optionalINS1_13unordered_mapIS7_NS1_7variantIJiS7_bEEENS1_4hashIS7_EENS1_8equal_toIS7_EENS5_INS1_4pairIKS7_SB_EEEEEEEE", 145656672},
    // ServerInstance
    {"_ZN14ServerInstance16initializeServerEO27ServerInstanceInitArguments", 166015056},
    // ServerNetworkHandler
    {"_ZN20ServerNetworkHandler15tryToLoadPlayerER12ServerPlayerRK17ConnectionRequestRK24PlayerAuthenticationInfo", 143837568},
    {"_ZN20ServerNetworkHandler20_validateLoginPacketERK17NetworkIdentifierRK11LoginPacket", 143755136},
    {"_ZN20ServerNetworkHandler24updateServerAnnouncementEv", 143739984},
    {"_ZN20ServerNetworkHandler27disconnectClientWithMessageERK17NetworkIdentifier11SubClientIdN10Connection20DisconnectFailReasonERKNSt3__112basic_stringIcNS6_11char_traitsIcEENS6_9allocatorIcEEEENS6_8optionalISC_EE", 143674352},
    // ServerPlayer
    {"_ZN12ServerPlayer15changeDimensionE13DimensionType", 166160176},
    // ServerScoreboard
    {"_ZN16ServerScoreboardC2E23CommandSoftEnumRegistryP12LevelStorageN3gsl8not_nullIN7Bedrock15NonOwnerPointerI19GameplayUserManagerEEEE", 217579792},
    // WeatherManager
    {"_ZN14WeatherManager13updateWeatherEfifi", 209726576},
    // webrtc::P2PTransportChannel
    {"_ZN6webrtc19P2PTransportChannel32SwitchSelectedConnectionInternalEPNS_10ConnectionENS_15IceSwitchReasonE", 68701648},
    // webrtc::Port
    {"_ZN6webrtc4Port24SendBindingErrorResponseEPNS_11StunMessageERKNS_13SocketAddressEiNSt3__117basic_string_viewIcNS6_11char_traitsIcEEEE", 68418112},
}};

}  // namespace endstone::runtime

// NOLINTEND
// clang-format on
