// Generated by scripts/dump_symbols.py for BDS 1.26.44 (linux). DO NOT EDIT.
// clang-format off
// NOLINTBEGIN

#pragma once

#include <array>
#include <cstddef>
#include <string_view>
#include <utility>

namespace endstone::runtime {

static constexpr std::array<std::pair<std::string_view, std::size_t>, 66> symbols = {{
    {"BlockState::StateListNode::mHead", 245468000},
    {"Enchant::mEnchants", 245294016},
    {"MobEffect::mMobEffects", 245274360},
    {"Potion::mPotionsById", 245353632},
    {"getI18n::result", 244110448},
    // Actor
    {"_ZN5Actor10teleportToERK4Vec3biib", 180244464},
    {"_ZN5Actor9addEffectERK17MobEffectInstance", 180384480},
    // ActorFactory
    {"_ZN12ActorFactory18createSpawnedActorERK25ActorDefinitionIdentifierP5ActorRK4Vec3RK4Vec2", 178030944},
    // BatchedNetworkPeer
    {"_ZN18BatchedNetworkPeer10sendPacketERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEN11NetworkPeer11ReliabilityE15Compressibility", 115687712},
    {"_ZN18BatchedNetworkPeer14_receivePacketERNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERKNS0_10shared_ptrINS0_6chrono10time_pointINS9_12steady_clockENS9_8durationIxNS0_5ratioILl1ELl1000000000EEEEEEEEE", 115688128},
    // BedrockLog::LogDetails
    {"_ZN10BedrockLog10LogDetails7_log_vaE9LogAreaIDjPKciiS3_P13__va_list_tag", 237069760},
    // BlockDescriptor::ResolveHelper
    {"_ZN15BlockDescriptor13ResolveHelper7resolveEb", 200714528},
    // BlockType
    {"_ZNK9BlockType14spawnResourcesER11BlockSourceRK8BlockPosRK5BlockR7IRandomRK20ResourceDropsContextPK5Actor", 199391376},
    {"_ZNK9BlockType25tryGetStateFromLegacyDataEt", 199383024},
    // BlockTypeRegistry
    {"_ZNK17BlockTypeRegistry16forEachBlockTypeEN5brstd12function_refIFbRK9BlockTypeES5_EE", 203856688},
    // CampfireBlockActor
    {"_ZN18CampfireBlockActor14_finishCookingER11BlockSourcei", 207808544},
    // Command
    {"_ZNK7Command3runERK13CommandOriginR13CommandOutput", 160430576},
    // CommandOriginLoader
    {"_ZN19CommandOriginLoader4loadERK11CompoundTagR11ServerLevel", 160490896},
    // CommandRegistry
    {"_ZN15CommandRegistry13addEnumValuesERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERKNS0_6vectorIS6_NS4_IS6_EEEE", 159955376},
    {"_ZN15CommandRegistry13registerAliasENSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEES6_", 159971792},
    {"_ZN15CommandRegistry15registerCommandERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEPKc22CommandPermissionLevel11CommandFlagSC_", 159961664},
    {"_ZN15CommandRegistry24registerOverloadInternalERNS_9SignatureERNS_8OverloadE", 159975664},
    {"_ZNK15CommandRegistry14symbolToStringENS_6SymbolE", 159852320},
    {"_ZNK15CommandRegistry26serializeAvailableCommandsEv", 160039360},
    // CommandUtils
    {"_ZN12CommandUtils12getActorNameERK5Actor", 159774800},
    // CraftingDataPacketPayload
    {"_ZN25CraftingDataPacketPayload11fromRecipesERK7Recipesb", 134785984},
    // DedicatedServer
    {"_ZN15DedicatedServer5startERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERKN7Bedrock19ActivationArgumentsE", 71550016},
    // DimensionManager
    {"_ZN16DimensionManager29serverRegisterCustomDimensionENSt3__117basic_string_viewIcNS0_11char_traitsIcEEEERKN3mce4UUIDE", 202063456},
    // Explosion
    {"_ZN9Explosion7explodeER7IRandom", 202093568},
    // FurnaceBlockActor
    {"_ZN17FurnaceBlockActor15getBurnDurationERK13ItemStackBasef", 207577216},
    // InventoryTransaction
    {"_ZN20InventoryTransaction23executeWorldInteractionEPvR6PlayerRK15InventoryAction", 197769664},
    // Item
    {"_ZNK4Item12readUserDataER13ItemStackBaseR10IDataInputR20ReadOnlyBinaryStream", 197130208},
    // ItemFrameBlockActor
    {"_ZN19ItemFrameBlockActor7setItemER11BlockSourceRK12ItemInstanceP5Actor", 207619568},
    // ItemInstance
    {"_ZN12ItemInstance7fromTagERK11CompoundTag", 196792144},
    // ItemRegistry
    {"_ZNK12ItemRegistry12lookupByNameERiNSt3__117basic_string_viewIcNS1_11char_traitsIcEEEE", 191714080},
    // ItemStackBase
    {"_ZN13ItemStackBase34_loadBlocksForCanPlaceOnCanDestroyERNSt3__16vectorIPK9BlockTypeNS0_9allocatorIS4_EEEERKNS0_12basic_stringIcNS0_11char_traitsIcEENS5_IcEEEE", 196858752},
    {"_ZN13ItemStackBase8_setItemEib", 196818048},
    // LeavesBlock
    {"_ZN11LeavesBlock10randomTickERN11BlockEvents20BlockRandomTickEventE", 199008832},
    // Level
    {"_ZN5Level4tickEv", 201848272},
    // LiquidBlock
    {"_ZNK11LiquidBlock12_trySpreadToER11BlockSourceRK8BlockPosiS4_h", 198739360},
    // MapDataManager
    {"_ZN14MapDataManager15getMapSavedDataE13ActorUniqueID", 201900800},
    // MinecraftCommands
    {"_ZN17MinecraftCommands14compileCommandERK12HashedStringR13CommandOrigin17CurrentCmdVersionNSt3__18functionIFvRKNS6_12basic_stringIcNS6_11char_traitsIcEENS6_9allocatorIcEEEEEEE", 160147088},
    {"_ZNK17MinecraftCommands14executeCommandER14CommandContextb", 160093584},
    // MinecraftPackets
    {"_ZN16MinecraftPackets12createPacketE18MinecraftPacketIds", 140175216},
    // Mob
    {"_ZN3Mob9knockbackEP5ActorfffRK19KnockbackParameters", 191349696},
    // PistonBlockActor
    {"_ZN16PistonBlockActor4tickER11BlockSource", 207194672},
    // Player
    {"_ZN6Player10teleportToERK4Vec3biib", 188137216},
    {"_ZN6Player13addExperienceEi", 188297776},
    {"_ZN6Player15startSleepInBedERK8BlockPosbf", 188144032},
    {"_ZN6Player17completeUsingItemEv", 188167680},
    {"_ZN6Player4dropERK9ItemStackb", 188279872},
    {"_ZN6Player4takeER5Actorii", 188227136},
    {"_ZN6Player9addLevelsEi", 188298880},
    // RakPeerHelper
    {"_ZN13RakPeerHelper11peerStartupEPN6RakNet16RakPeerInterfaceERK20ConnectionDefinitionNS_11PeerPurposeE", 140305792},
    // RepositoryFactory
    {"_ZNK17RepositoryFactory13createSourcesERK23IResourcePackRepository", 157557584},
    // SayCommand
    {"_ZN10SayCommand12_sendMessageERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERKNS0_8optionalIS6_EES8_RK21CommandOriginIdentityR5Level", 158351216},
    // ScriptModuleMinecraft::ScriptBlockUtils
    {"_ZN21ScriptModuleMinecraft16ScriptBlockUtils21createBlockDescriptorENSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS1_8optionalINS1_13unordered_mapIS7_NS1_7variantIJiS7_bEEENS1_4hashIS7_EENS1_8equal_toIS7_EENS5_INS1_4pairIKS7_SB_EEEEEEEE", 140884080},
    // ServerInstance
    {"_ZN14ServerInstance16initializeServerEO27ServerInstanceInitArguments", 161657568},
    // ServerNetworkHandler
    {"_ZN20ServerNetworkHandler15tryToLoadPlayerER12ServerPlayerRK17ConnectionRequestRK24PlayerAuthenticationInfo", 139461632},
    {"_ZN20ServerNetworkHandler20_validateLoginPacketERK17NetworkIdentifierRK11LoginPacket", 139379920},
    {"_ZN20ServerNetworkHandler24updateServerAnnouncementEv", 139364864},
    {"_ZN20ServerNetworkHandler27disconnectClientWithMessageERK17NetworkIdentifier11SubClientIdN10Connection20DisconnectFailReasonERKNSt3__112basic_stringIcNS6_11char_traitsIcEENS6_9allocatorIcEEEENS6_8optionalISC_EE", 139301376},
    // ServerPlayer
    {"_ZN12ServerPlayer15changeDimensionE13DimensionType", 160365232},
    // ServerScoreboard
    {"_ZN16ServerScoreboardC2E23CommandSoftEnumRegistryP12LevelStorageN3gsl8not_nullIN7Bedrock15NonOwnerPointerI19GameplayUserManagerEEEE", 209066992},
    // TridentItem
    {"_ZNK11TridentItem12releaseUsingER9ItemStackP6Playeri", 195973728},
    // WeatherManager
    {"_ZN14WeatherManager13updateWeatherEfifi", 201402304},
}};

}  // namespace endstone::runtime

// NOLINTEND
// clang-format on
