// Generated by scripts/dump_symbols.py for BDS 1.26.51 (windows). DO NOT EDIT.
// clang-format off
// NOLINTBEGIN

#pragma once

#include <array>
#include <cstddef>
#include <string_view>
#include <utility>

namespace endstone::runtime {

static constexpr std::array<std::pair<std::string_view, std::size_t>, 64> symbols = {{
    {"BlockState::StateListNode::mHead", 215088112},
    {"Enchant::mEnchants", 214652808},
    // Actor
    {"?teleportTo@Actor@@UEAAXAEBVVec3@@_NHH1@Z", 13861632},
    // ActorFactory
    {"?createSpawnedActor@ActorFactory@@QEAA?AV?$OwnerPtr@VEntityContext@@@@AEBUActorDefinitionIdentifier@@PEAVActor@@AEBVVec3@@AEBVVec2@@@Z", 30318048},
    // BatchedNetworkPeer
    {"?_receivePacket@BatchedNetworkPeer@@MEAA?AW4DataStatus@NetworkPeer@@AEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV?$shared_ptr@V?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@chrono@std@@@5@@Z", 11073456},
    {"?sendPacket@BatchedNetworkPeer@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4Reliability@NetworkPeer@@W4Compressibility@@@Z", 11072976},
    // BedrockLog::LogDetails
    {"?_log_va@LogDetails@BedrockLog@@AEAAXW4LogAreaID@@IPEBDHH1PEAD@Z", 2546192},
    // BlockDescriptor::ResolveHelper
    {"?resolve@ResolveHelper@BlockDescriptor@@QEAAX_N@Z", 47144992},
    // BlockType
    {"?spawnResources@BlockType@@QEBAXAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@AEAVIRandom@@AEBUResourceDropsContext@@PEBVActor@@@Z", 27409008},
    {"?tryGetStateFromLegacyData@BlockType@@QEBAPEBVBlock@@G@Z", 27400016},
    // BlockTypeRegistry
    {"?forEachBlockType@BlockTypeRegistry@@QEBAXV?$function_ref@$$A6A_NAEBVBlockType@@@Z$$A6A_N0@Z@brstd@@@Z", 26979856},
    // CampfireBlockActor
    {"?_finishCooking@CampfireBlockActor@@AEAAXAEAVBlockSource@@H@Z", 32663744},
    // Command
    {"?run@Command@@QEBAXAEBVCommandOrigin@@AEAVCommandOutput@@@Z", 18863632},
    // CommandOriginLoader
    {"?load@CommandOriginLoader@@SA?AV?$unique_ptr@VCommandOrigin@@U?$default_delete@VCommandOrigin@@@std@@@std@@AEBVCompoundTag@@AEAVServerLevel@@@Z", 18931120},
    // CommandRegistry
    {"?addEnumValues@CommandRegistry@@QEAAHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@3@@Z", 19148064},
    {"?registerAlias@CommandRegistry@@QEAAXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z", 19167824},
    {"?registerCommand@CommandRegistry@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEBDW4CommandPermissionLevel@@UCommandFlag@@3@Z", 19155184},
    {"?registerOverloadInternal@CommandRegistry@@AEAAXAEAUSignature@1@AEAUOverload@1@@Z", 19172768},
    {"?serializeAvailableCommands@CommandRegistry@@QEBA?AVAvailableCommandsPacket@@XZ", 19232400},
    {"?symbolToString@CommandRegistry@@AEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VSymbol@1@@Z", 18861376},
    // CommandUtils
    {"?getActorName@CommandUtils@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVActor@@@Z", 4035184},
    // CraftingDataPacketPayload
    {"?fromRecipes@CraftingDataPacketPayload@@SA?AU1@AEBVRecipes@@_N@Z", 51738592},
    // DedicatedServer
    {"?start@DedicatedServer@@QEAA?AW4ServerExitCode@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVActivationArguments@Bedrock@@@Z", 501616},
    // Explosion
    {"?explode@Explosion@@QEAA_NAEAVIRandom@@@Z", 7952016},
    // FurnaceBlockActor
    {"?getBurnDuration@FurnaceBlockActor@@SAMAEBVItemStackBase@@M@Z", 92218928},
    // InventoryTransaction
    {"?executeWorldInteraction@InventoryTransaction@@SA?AW4InventoryTransactionError@@PEAXAEAVPlayer@@AEBVInventoryAction@@@Z", 44608944},
    // Item
    {"?readUserData@Item@@UEBAXAEAVItemStackBase@@AEAVIDataInput@@AEAVReadOnlyBinaryStream@@@Z", 27851120},
    // ItemInstance
    {"?fromTag@ItemInstance@@SA?AV1@AEBVCompoundTag@@@Z", 27952608},
    // ItemRegistry
    {"?lookupByName@ItemRegistry@@AEBA?AV?$WeakPtr@VItem@@@@AEAHV?$basic_string_view@DU?$char_traits@D@std@@@std@@@Z", 23249440},
    // ItemStackBase
    {"?_loadBlocksForCanPlaceOnCanDestroy@ItemStackBase@@CA_NAEAV?$vector@PEBVBlockType@@V?$allocator@PEBVBlockType@@@std@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@@Z", 27645648},
    {"?_setItem@ItemStackBase@@AEAA_NH_N@Z", 27608816},
    // LeavesBlock
    {"?randomTick@LeavesBlock@@QEBAXAEAVBlockRandomTickEvent@BlockEvents@@@Z", 50196368},
    // Level
    {"?tick@Level@@UEAAXXZ", 8175568},
    // LiquidBlock
    {"?_trySpreadTo@LiquidBlock@@IEBAXAEAVBlockSource@@AEBVBlockPos@@H1E@Z", 146137472},
    // MapDataManager
    {"?_loadMapData@MapDataManager@@IEAAPEAVMapItemSavedData@@AEBUActorUniqueID@@@Z", 8750416},
    // MinecraftCommands
    {"?compileCommand@MinecraftCommands@@QEAAPEAVCommand@@AEBVHashedString@@AEAVCommandOrigin@@W4CurrentCmdVersion@@V?$function@$$A6AXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z@std@@@Z", 4099168},
    {"?executeCommand@MinecraftCommands@@QEBA?AUMCRESULT@@AEAVCommandContext@@_N@Z", 4039904},
    // MinecraftPackets
    {"?createPacket@MinecraftPackets@@SA?AV?$shared_ptr@VPacket@@@std@@W4MinecraftPacketIds@@@Z", 9675920},
    // Mob
    {"?knockback@Mob@@UEAAXPEAVActor@@MMMAEBUKnockbackParameters@@@Z", 43937952},
    // NetherNet::LanThreadManager
    {"?SendLanBroadcastResponse@LanThreadManager@NetherNet@@UEAAXAEBVSocketAddress@webrtc@@UNetworkID@2@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z", 17962688},
    // NetherNet::SimpleNetworkInterfaceImpl
    {"?ReceiveFromSignalingChannel@SimpleNetworkInterfaceImpl@NetherNet@@AEAAXUNetworkID@2@V?$basic_string_view@DU?$char_traits@D@std@@@std@@W4SignalingChannelId@2@@Z", 18010560},
    // NetworkSystem
    {"?send@NetworkSystem@@QEAAXAEBVNetworkIdentifier@@AEBVPacket@@W4SubClientId@@@Z", 9687248},
    // PistonBlockActor
    {"?tick@PistonBlockActor@@UEAAXAEAVBlockSource@@@Z", 75966528},
    // Player
    {"?completeUsingItem@Player@@QEAAXXZ", 2786992},
    {"?drop@Player@@UEAA_NAEBVItemStack@@_N@Z", 2872160},
    {"?startSleepInBed@Player@@UEAA?AW4BedSleepingResult@@AEBVBlockPos@@_NM@Z", 2761888},
    {"?stopSleepInBed@Player@@UEAAX_N0@Z", 2767280},
    {"?take@Player@@QEAA_NAEAVActor@@HH@Z", 2837264},
    {"?teleportTo@Player@@UEAAXAEBVVec3@@_NHH1@Z", 2755600},
    // RakNet::RNS2_Windows_Linux_360
    {"?Send_Windows_Linux_360NoVDP@RNS2_Windows_Linux_360@RakNet@@KAHHPEAURNS2_SendParameters@2@PEBDI@Z", 54713040},
    // RakPeerHelper
    {"?peerStartup@RakPeerHelper@@QEAA?AW4StartupResult@RakNet@@PEAVRakPeerInterface@3@AEBUConnectionDefinition@@W4PeerPurpose@1@@Z", 9799424},
    // RepositoryFactory
    {"?createSources@RepositoryFactory@@UEBA?AV?$shared_ptr@VRepositorySources@@@std@@AEBVIResourcePackRepository@@@Z", 13101168},
    // SayCommand
    {"?_sendMessage@SayCommand@@CAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV?$optional@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@3@0AEBUCommandOriginIdentity@@AEAVLevel@@@Z", 61897296},
    // ScriptModuleMinecraft::ScriptBlockUtils
    {"?createBlockDescriptor@ScriptBlockUtils@ScriptModuleMinecraft@@YA?AVBlockDescriptor@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$optional@V?$unordered_map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$variant@HV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@2@U?$hash@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@U?$equal_to@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$variant@HV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@2@@std@@@2@@std@@@5@@Z", 69650352},
    // ServerInstance
    {"?initializeServer@ServerInstance@@QEAA?AUServerInitResult@ServerInitialization@@$$QEAUServerInstanceInitArguments@@@Z", 7530400},
    // ServerNetworkHandler
    {"?_validateLoginPacket@ServerNetworkHandler@@EEAA?AV?$optional@UPlayerAuthenticationInfo@@@std@@AEBVNetworkIdentifier@@AEBVLoginPacket@@@Z", 9998656},
    {"?disconnectClientWithMessage@ServerNetworkHandler@@QEAAXAEBVNetworkIdentifier@@W4SubClientId@@W4DisconnectFailReason@Connection@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$optional@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@7@@Z", 9908032},
    {"?tryToLoadPlayer@ServerNetworkHandler@@QEAA_NAEAVServerPlayer@@AEBVConnectionRequest@@AEBUPlayerAuthenticationInfo@@@Z", 10094224},
    {"?updateServerAnnouncement@ServerNetworkHandler@@QEAAXXZ", 9978160},
    // ServerPlayer
    {"?changeDimension@ServerPlayer@@UEAAXUDimensionType@@@Z", 7705664},
    // ServerScoreboard
    {"??0ServerScoreboard@@QEAA@VCommandSoftEnumRegistry@@PEAVLevelStorage@@V?$not_null@V?$NonOwnerPointer@VGameplayUserManager@@@Bedrock@@@gsl@@@Z", 2095792},
    // WeatherManager
    {"?updateWeather@WeatherManager@@QEAAXMHMH@Z", 18477376},
    // YAAEAVI18n
    {"?getI18n@@YAAEAVI18n@@XZ", 1146848},
    // webrtc::P2PTransportChannel
    {"?SwitchSelectedConnectionInternal@P2PTransportChannel@webrtc@@AEAAXPEAVConnection@2@W4IceSwitchReason@2@@Z", 171292176},
}};

}  // namespace endstone::runtime

// NOLINTEND
// clang-format on
