// Generated by scripts/dump_symbols.py for BDS 1.26.44 (windows). DO NOT EDIT.
// clang-format off
// NOLINTBEGIN

#pragma once

#include <array>
#include <cstddef>
#include <string_view>
#include <utility>

namespace endstone::runtime {

static constexpr std::array<std::pair<std::string_view, std::size_t>, 67> symbols = {{
    {"BlockState::StateListNode::mHead", 211294960},
    {"Enchant::mEnchants", 211141912},
    {"MobEffect::mMobEffects", 211424880},
    {"Potion::mPotionsById", 211501744},
    // Actor
    {"?addEffect@Actor@@QEAAXAEBVMobEffectInstance@@@Z", 14790208},
    {"?teleportTo@Actor@@UEAAXAEBVVec3@@_NHH1@Z", 14658832},
    // ActorFactory
    {"?createSpawnedActor@ActorFactory@@QEAA?AV?$OwnerPtr@VEntityContext@@@@AEBUActorDefinitionIdentifier@@PEAVActor@@AEBVVec3@@AEBVVec2@@@Z", 26276384},
    // ArmorStand
    {"?getInteraction@ArmorStand@@UEAA?AVInteractionResult@@AEAVPlayer@@AEAVActorInteraction@@AEBVVec3@@@Z", 37474192},
    // BatchedNetworkPeer
    {"?_receivePacket@BatchedNetworkPeer@@MEAA?AW4DataStatus@NetworkPeer@@AEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV?$shared_ptr@V?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@chrono@std@@@5@@Z", 16659136},
    {"?sendPacket@BatchedNetworkPeer@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4Reliability@NetworkPeer@@W4Compressibility@@@Z", 16658656},
    // BedrockLog::LogDetails
    {"?_log_va@LogDetails@BedrockLog@@AEAAXW4LogAreaID@@IPEBDHH1PEAD@Z", 1890144},
    // BlockDescriptor::ResolveHelper
    {"?resolve@ResolveHelper@BlockDescriptor@@QEAAX_N@Z", 75234016},
    // BlockType
    {"?spawnResources@BlockType@@QEBAXAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@AEAVIRandom@@AEBUResourceDropsContext@@PEBVActor@@@Z", 32431200},
    {"?tryGetStateFromLegacyData@BlockType@@QEBAPEBVBlock@@G@Z", 32421904},
    // BlockTypeRegistry
    {"?forEachBlockType@BlockTypeRegistry@@QEBAXV?$function_ref@$$A6A_NAEBVBlockType@@@Z$$A6A_N0@Z@brstd@@@Z", 42281168},
    // CampfireBlockActor
    {"?_finishCooking@CampfireBlockActor@@AEAAXAEAVBlockSource@@H@Z", 43046640},
    // Command
    {"?run@Command@@QEBAXAEBVCommandOrigin@@AEAVCommandOutput@@@Z", 19785792},
    // CommandOriginLoader
    {"?load@CommandOriginLoader@@SA?AV?$unique_ptr@VCommandOrigin@@U?$default_delete@VCommandOrigin@@@std@@@std@@AEBVCompoundTag@@AEAVServerLevel@@@Z", 19857792},
    // CommandRegistry
    {"?addEnumValues@CommandRegistry@@QEAAHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@3@@Z", 3561872},
    {"?registerAlias@CommandRegistry@@QEAAXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z", 3584080},
    {"?registerCommand@CommandRegistry@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEBDW4CommandPermissionLevel@@UCommandFlag@@3@Z", 3570400},
    {"?registerOverloadInternal@CommandRegistry@@AEAAXAEAUSignature@1@AEAUOverload@1@@Z", 3589280},
    {"?serializeAvailableCommands@CommandRegistry@@QEBA?AVAvailableCommandsPacket@@XZ", 3654624},
    {"?symbolToString@CommandRegistry@@AEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VSymbol@1@@Z", 3423632},
    // CommandUtils
    {"?getActorName@CommandUtils@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVActor@@@Z", 3711424},
    // CraftingDataPacketPayload
    {"?fromRecipes@CraftingDataPacketPayload@@SA?AU1@AEBVRecipes@@_N@Z", 39627104},
    // DedicatedServer
    {"?start@DedicatedServer@@QEAA?AW4ServerExitCode@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVActivationArguments@Bedrock@@@Z", 501600},
    // DimensionManager
    {"?serverRegisterCustomDimension@DimensionManager@@QEAA?AV?$optional@UDimensionType@@@std@@V?$basic_string_view@DU?$char_traits@D@std@@@3@AEBVUUID@mce@@@Z", 7151824},
    // Explosion
    {"?explode@Explosion@@QEAA_NAEAVIRandom@@@Z", 7190560},
    // FurnaceBlockActor
    {"?getBurnDuration@FurnaceBlockActor@@SAMAEBVItemStackBase@@M@Z", 99471088},
    // InventoryTransaction
    {"?executeWorldInteraction@InventoryTransaction@@SA?AW4InventoryTransactionError@@PEAXAEAVPlayer@@AEBVInventoryAction@@@Z", 39521808},
    // Item
    {"?readUserData@Item@@UEBAXAEAVItemStackBase@@AEAVIDataInput@@AEAVReadOnlyBinaryStream@@@Z", 38732512},
    // ItemFrameBlockActor
    {"?setItem@ItemFrameBlockActor@@QEAAXAEAVBlockSource@@AEBVItemInstance@@PEAVActor@@@Z", 99506736},
    // ItemInstance
    {"?fromTag@ItemInstance@@SA?AV1@AEBVCompoundTag@@@Z", 29101360},
    // ItemRegistry
    {"?lookupByName@ItemRegistry@@AEBA?AV?$WeakPtr@VItem@@@@AEAHV?$basic_string_view@DU?$char_traits@D@std@@@std@@@Z", 22181760},
    // ItemStackBase
    {"?_loadBlocksForCanPlaceOnCanDestroy@ItemStackBase@@CA_NAEAV?$vector@PEBVBlockType@@V?$allocator@PEBVBlockType@@@std@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@@Z", 29168176},
    {"?_setItem@ItemStackBase@@AEAA_NH_N@Z", 29129472},
    // LeavesBlock
    {"?randomTick@LeavesBlock@@QEBAXAEAVBlockRandomTickEvent@BlockEvents@@@Z", 48292160},
    // Level
    {"?tick@Level@@UEAAXXZ", 7554960},
    // LiquidBlock
    {"?_trySpreadTo@LiquidBlock@@IEBAXAEAVBlockSource@@AEBVBlockPos@@H1E@Z", 48333664},
    // MapDataManager
    {"?_loadMapData@MapDataManager@@IEAAPEAVMapItemSavedData@@AEBUActorUniqueID@@@Z", 7658336},
    // MinecraftCommands
    {"?compileCommand@MinecraftCommands@@QEAAPEAVCommand@@AEBVHashedString@@AEAVCommandOrigin@@W4CurrentCmdVersion@@V?$function@$$A6AXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z@std@@@Z", 3780512},
    {"?executeCommand@MinecraftCommands@@QEBA?AUMCRESULT@@AEAVCommandContext@@_N@Z", 3716416},
    // MinecraftPackets
    {"?createPacket@MinecraftPackets@@SA?AV?$shared_ptr@VPacket@@@std@@W4MinecraftPacketIds@@@Z", 12540224},
    // Mob
    {"?knockback@Mob@@UEAAXPEAVActor@@MMMAEBUKnockbackParameters@@@Z", 37752464},
    // PistonBlockActor
    {"?tick@PistonBlockActor@@UEAAXAEAVBlockSource@@@Z", 99573264},
    // Player
    {"?addExperience@Player@@UEAAXH@Z", 2318544},
    {"?addLevels@Player@@UEAAXH@Z", 2320016},
    {"?completeUsingItem@Player@@QEAAXXZ", 2206272},
    {"?drop@Player@@UEAA_NAEBVItemStack@@_N@Z", 2302400},
    {"?startSleepInBed@Player@@UEAA?AW4BedSleepingResult@@AEBVBlockPos@@_NM@Z", 2182176},
    {"?take@Player@@QEAA_NAEAVActor@@HH@Z", 2251552},
    {"?teleportTo@Player@@UEAAXAEBVVec3@@_NHH1@Z", 2176288},
    // RakPeerHelper
    {"?peerStartup@RakPeerHelper@@QEAA?AW4StartupResult@RakNet@@PEAVRakPeerInterface@3@AEBUConnectionDefinition@@W4PeerPurpose@1@@Z", 12705152},
    // RepositoryFactory
    {"?createSources@RepositoryFactory@@UEBA?AV?$shared_ptr@VRepositorySources@@@std@@AEBVIResourcePackRepository@@@Z", 14441632},
    // SayCommand
    {"?_sendMessage@SayCommand@@CAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV?$optional@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@3@0AEBUCommandOriginIdentity@@AEAVLevel@@@Z", 64464304},
    // ScriptModuleMinecraft::ScriptBlockUtils
    {"?createBlockDescriptor@ScriptBlockUtils@ScriptModuleMinecraft@@YA?AVBlockDescriptor@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$optional@V?$unordered_map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$variant@HV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@2@U?$hash@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@U?$equal_to@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$variant@HV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@2@@std@@@2@@std@@@5@@Z", 93045328},
    // ServerInstance
    {"?initializeServer@ServerInstance@@QEAA?AUServerInitResult@ServerInitialization@@$$QEAUServerInstanceInitArguments@@@Z", 6745984},
    // ServerNetworkHandler
    {"?_validateLoginPacket@ServerNetworkHandler@@EEAA?AV?$optional@UPlayerAuthenticationInfo@@@std@@AEBVNetworkIdentifier@@AEBVLoginPacket@@@Z", 10976368},
    {"?disconnectClientWithMessage@ServerNetworkHandler@@QEAAXAEBVNetworkIdentifier@@W4SubClientId@@W4DisconnectFailReason@Connection@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$optional@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@7@@Z", 10884240},
    {"?tryToLoadPlayer@ServerNetworkHandler@@QEAA_NAEAVServerPlayer@@AEBVConnectionRequest@@AEBUPlayerAuthenticationInfo@@@Z", 11072160},
    {"?updateServerAnnouncement@ServerNetworkHandler@@QEAAXXZ", 10953072},
    // ServerPlayer
    {"?changeDimension@ServerPlayer@@UEAAXUDimensionType@@@Z", 6907440},
    // ServerScoreboard
    {"??0ServerScoreboard@@QEAA@VCommandSoftEnumRegistry@@PEAVLevelStorage@@V?$not_null@V?$NonOwnerPointer@VGameplayUserManager@@@Bedrock@@@gsl@@@Z", 1277104},
    // TridentItem
    {"?releaseUsing@TridentItem@@UEBAXAEAVItemStack@@PEAVPlayer@@H@Z", 53278064},
    // WeatherManager
    {"?updateWeather@WeatherManager@@QEAAXMHMH@Z", 19355200},
    // YAAEAVI18n
    {"?getI18n@@YAAEAVI18n@@XZ", 6057456},
}};

}  // namespace endstone::runtime

// NOLINTEND
// clang-format on
