// Generated by scripts/dump_symbols.py for BDS 1.26.40 (windows). DO NOT EDIT.
// clang-format off
// NOLINTBEGIN

#pragma once

#include <array>
#include <cstddef>
#include <string_view>
#include <utility>

namespace endstone::runtime {

static constexpr std::array<std::pair<std::string_view, std::size_t>, 61> symbols = {{
    {"BlockState::StateListNode::mHead", 211163888},
    {"Enchant::mEnchants", 211010840},
    // Actor
    {"?teleportTo@Actor@@UEAAXAEBVVec3@@_NHH1@Z", 14649472},
    // ActorFactory
    {"?createSpawnedActor@ActorFactory@@QEAA?AV?$OwnerPtr@VEntityContext@@@@AEBUActorDefinitionIdentifier@@PEAVActor@@AEBVVec3@@AEBVVec2@@@Z", 26255264},
    // BatchedNetworkPeer
    {"?_receivePacket@BatchedNetworkPeer@@MEAA?AW4DataStatus@NetworkPeer@@AEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV?$shared_ptr@V?$time_point@Usteady_clock@chrono@std@@V?$duration@_JU?$ratio@$00$0DLJKMKAA@@std@@@23@@chrono@std@@@5@@Z", 16646608},
    {"?sendPacket@BatchedNetworkPeer@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4Reliability@NetworkPeer@@W4Compressibility@@@Z", 16646128},
    // BedrockLog::LogDetails
    {"?_log_va@LogDetails@BedrockLog@@AEAAXW4LogAreaID@@IPEBDHH1PEAD@Z", 1890144},
    // BlockDescriptor::ResolveHelper
    {"?resolve@ResolveHelper@BlockDescriptor@@QEAAX_N@Z", 75178160},
    // BlockType
    {"?spawnResources@BlockType@@QEBAXAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@AEAVIRandom@@AEBUResourceDropsContext@@PEBVActor@@@Z", 32417408},
    {"?tryGetStateFromLegacyData@BlockType@@QEBAPEBVBlock@@G@Z", 32408112},
    // BlockTypeRegistry
    {"?forEachBlockType@BlockTypeRegistry@@QEBAXV?$function_ref@$$A6A_NAEBVBlockType@@@Z$$A6A_N0@Z@brstd@@@Z", 42259040},
    // CampfireBlockActor
    {"?_finishCooking@CampfireBlockActor@@AEAAXAEAVBlockSource@@H@Z", 43024512},
    // Command
    {"?run@Command@@QEBAXAEBVCommandOrigin@@AEAVCommandOutput@@@Z", 19772480},
    // CommandOriginLoader
    {"?load@CommandOriginLoader@@SA?AV?$unique_ptr@VCommandOrigin@@U?$default_delete@VCommandOrigin@@@std@@@std@@AEBVCompoundTag@@AEAVServerLevel@@@Z", 19844480},
    // CommandRegistry
    {"?addEnumValues@CommandRegistry@@QEAAHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@3@@Z", 3561888},
    {"?registerAlias@CommandRegistry@@QEAAXV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z", 3584096},
    {"?registerCommand@CommandRegistry@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEBDW4CommandPermissionLevel@@UCommandFlag@@3@Z", 3570416},
    {"?registerOverloadInternal@CommandRegistry@@AEAAXAEAUSignature@1@AEAUOverload@1@@Z", 3589296},
    {"?serializeAvailableCommands@CommandRegistry@@QEBA?AVAvailableCommandsPacket@@XZ", 3654640},
    {"?symbolToString@CommandRegistry@@AEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VSymbol@1@@Z", 3423648},
    // CommandUtils
    {"?getActorName@CommandUtils@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVActor@@@Z", 3711472},
    // CraftingDataPacket
    {"?prepareFromRecipes@CraftingDataPacket@@SA?AUCraftingDataPacketPayload@@AEBVRecipes@@_N@Z", 39607088},
    // DedicatedServer
    {"?start@DedicatedServer@@QEAA?AW4ServerExitCode@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVActivationArguments@Bedrock@@@Z", 501600},
    // Explosion
    {"?explode@Explosion@@QEAA_NAEAVIRandom@@@Z", 7188048},
    // FurnaceBlockActor
    {"?getBurnDuration@FurnaceBlockActor@@SAMAEBVItemStackBase@@M@Z", 99401776},
    // InventoryTransaction
    {"?executeWorldInteraction@InventoryTransaction@@SA?AW4InventoryTransactionError@@PEAXAEAVPlayer@@AEBVInventoryAction@@@Z", 39501792},
    // Item
    {"?readUserData@Item@@UEBAXAEAVItemStackBase@@AEAVIDataInput@@AEAVReadOnlyBinaryStream@@@Z", 38712960},
    // ItemInstance
    {"?fromTag@ItemInstance@@SA?AV1@AEBVCompoundTag@@@Z", 1494353894},
    // ItemRegistry
    {"?lookupByName@ItemRegistry@@AEBA?AV?$WeakPtr@VItem@@@@AEAHV?$basic_string_view@DU?$char_traits@D@std@@@std@@@Z", 22160768},
    // ItemStackBase
    {"?_loadBlocksForCanPlaceOnCanDestroy@ItemStackBase@@CA_NAEAV?$vector@PEBVBlockType@@V?$allocator@PEBVBlockType@@@std@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@3@@Z", 29144736},
    {"?_setItem@ItemStackBase@@AEAA_NH_N@Z", 29106032},
    // LeavesBlock
    {"?randomTick@LeavesBlock@@QEBAXAEAVBlockRandomTickEvent@BlockEvents@@@Z", 48264352},
    // Level
    {"?tick@Level@@UEAAXXZ", 7552464},
    // LiquidBlock
    {"?_trySpreadTo@LiquidBlock@@IEBAXAEAVBlockSource@@AEBVBlockPos@@H1E@Z", 48305856},
    // MapDataManager
    {"?_loadMapData@MapDataManager@@IEAAPEAVMapItemSavedData@@AEBUActorUniqueID@@@Z", 7655840},
    // MinecraftCommands
    {"?compileCommand@MinecraftCommands@@QEAAPEAVCommand@@AEBVHashedString@@AEAVCommandOrigin@@W4CurrentCmdVersion@@V?$function@$$A6AXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z@std@@@Z", 3780560},
    {"?executeCommand@MinecraftCommands@@QEBA?AUMCRESULT@@AEAVCommandContext@@_N@Z", 3716464},
    // MinecraftPackets
    {"?createPacket@MinecraftPackets@@SA?AV?$shared_ptr@VPacket@@@std@@W4MinecraftPacketIds@@@Z", 12530432},
    // Mob
    {"?knockback@Mob@@UEAAXPEAVActor@@MMMAEBUKnockbackParameters@@@Z", 37732912},
    // NetworkSystem
    {"?send@NetworkSystem@@QEAAXAEBVNetworkIdentifier@@AEBVPacket@@W4SubClientId@@@Z", 12576928},
    // PistonBlockActor
    {"?tick@PistonBlockActor@@UEAAXAEAVBlockSource@@@Z", 99503952},
    // Player
    {"?completeUsingItem@Player@@QEAAXXZ", 2206272},
    {"?drop@Player@@UEAA_NAEBVItemStack@@_N@Z", 2302400},
    {"?startSleepInBed@Player@@UEAA?AW4BedSleepingResult@@AEBVBlockPos@@_NM@Z", 2182176},
    {"?stopSleepInBed@Player@@UEAAX_N0@Z", 2187632},
    {"?take@Player@@QEAA_NAEAVActor@@HH@Z", 2251552},
    {"?teleportTo@Player@@UEAAXAEBVVec3@@_NHH1@Z", 2176288},
    // RakNet::RNS2_Windows_Linux_360
    {"?Send_Windows_Linux_360NoVDP@RNS2_Windows_Linux_360@RakNet@@KAHHPEAURNS2_SendParameters@2@PEBDI@Z", 54736064},
    // RakPeerHelper
    {"?peerStartup@RakPeerHelper@@QEAA?AW4StartupResult@RakNet@@PEAVRakPeerInterface@3@AEBUConnectionDefinition@@W4PeerPurpose@1@@Z", 12695360},
    // RepositoryFactory
    {"?createSources@RepositoryFactory@@UEBA?AV?$shared_ptr@VRepositorySources@@@std@@AEBVIResourcePackRepository@@@Z", 14432272},
    // SayCommand
    {"?_sendMessage@SayCommand@@CAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV?$optional@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@3@0AEBUCommandOriginIdentity@@AEAVLevel@@@Z", 64416928},
    // ScriptModuleMinecraft::ScriptBlockUtils
    {"?createBlockDescriptor@ScriptBlockUtils@ScriptModuleMinecraft@@YA?AVBlockDescriptor@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$optional@V?$unordered_map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$variant@HV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@2@U?$hash@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@U?$equal_to@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$variant@HV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@2@@std@@@2@@std@@@5@@Z", 92975904},
    // ServerInstance
    {"?initializeServer@ServerInstance@@QEAA?AUServerInitResult@ServerInitialization@@$$QEAUServerInstanceInitArguments@@@Z", 6743712},
    // ServerNetworkHandler
    {"?_validateLoginPacket@ServerNetworkHandler@@EEAA?AV?$optional@UPlayerAuthenticationInfo@@@std@@AEBVNetworkIdentifier@@AEBVLoginPacket@@@Z", 10969664},
    {"?disconnectClientWithMessage@ServerNetworkHandler@@QEAAXAEBVNetworkIdentifier@@W4SubClientId@@W4DisconnectFailReason@Connection@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$optional@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@7@@Z", 10877536},
    {"?tryToLoadPlayer@ServerNetworkHandler@@QEAA_NAEAVServerPlayer@@AEBVConnectionRequest@@AEBUPlayerAuthenticationInfo@@@Z", 11065456},
    {"?updateServerAnnouncement@ServerNetworkHandler@@QEAAXXZ", 10946368},
    // ServerPlayer
    {"?changeDimension@ServerPlayer@@UEAAXUDimensionType@@@Z", 6905168},
    // ServerScoreboard
    {"??0ServerScoreboard@@QEAA@VCommandSoftEnumRegistry@@PEAVLevelStorage@@V?$not_null@V?$NonOwnerPointer@VGameplayUserManager@@@Bedrock@@@gsl@@@Z", 1277104},
    // WeatherManager
    {"?updateWeather@WeatherManager@@QEAAXMHMH@Z", 19341888},
    // YAAEAVI18n
    {"?getI18n@@YAAEAVI18n@@XZ", 6055184},
}};

}  // namespace endstone::runtime

// NOLINTEND
// clang-format on
