class ColorFormat:
    BLACK: str
    DARK_BLUE: str
    DARK_GREEN: str
    DARK_AQUA: str
    DARK_RED: str
    DARK_PURPLE: str
    GOLD: str
    GRAY: str
    DARK_GRAY: str
    BLUE: str
    GREEN: str
    AQUA: str
    RED: str
    LIGHT_PURPLE: str
    YELLOW: str
    WHITE: str
    MINECOIN_GOLD: str
    MATERIAL_QUARTZ: str
    MATERIAL_IRON: str
    MATERIAL_NETHERITE: str
    MATERIAL_REDSTONE: str
    MATERIAL_COPPER: str
    MATERIAL_GOLD: str
    MATERIAL_EMERALD: str
    MATERIAL_DIAMOND: str
    MATERIAL_LAPIS: str
    MATERIAL_AMETHYST: str
    OBFUSCATED: str
    BOLD: str
    ITALIC: str
    RESET: str
