from __future__ import annotations

from .actor import build_actor_scenarios
from .block import build_block_scenarios
from .gametest import build_gametest_scenarios
from .player import build_player_scenarios
from .server import build_server_scenarios


_SCENARIO_ORDER = {
    'gametest-actor-explode': 0,
    'gametest-actor-explode-cancel': 1,
    'gametest-actor-knockback': 2,
    'gametest-actor-knockback-cancel': 3,
    'gametest-block-explode': 4,
    'gametest-block-explode-cancel': 5,
    'gametest-simulated-block-place': 6,
    'gametest-simulated-block-place-cancel': 7,
    'gametest-simulated-block-break': 8,
    'gametest-simulated-block-break-cancel': 9,
    'gametest-simulated-block-interact': 10,
    'gametest-simulated-block-interact-cancel': 11,
    'gametest-simulated-bucket-fill': 12,
    'gametest-simulated-bucket-fill-cancel': 13,
    'gametest-simulated-bucket-empty': 14,
    'gametest-simulated-bucket-empty-cancel': 15,
    'gametest-simulated-cauldron-bucket-empty': 16,
    'gametest-simulated-cauldron-bucket-empty-cancel': 17,
    'gametest-simulated-inventory-open': 18,
    'gametest-simulated-inventory-open-cancel': 19,
    'gametest-simulated-bucket-actor': 20,
    'gametest-simulated-bucket-actor-cancel': 21,
    'gametest-simulated-armor-stand-manipulate': 22,
    'gametest-simulated-armor-stand-manipulate-cancel': 23,
    'gametest-simulated-shear-actor': 24,
    'gametest-simulated-shear-actor-cancel': 25,
    'gametest-simulated-item-consume': 26,
    'gametest-simulated-item-consume-cancel': 27,
    'server-command': 28,
    'server-command-cancel': 29,
    'broadcast-message': 30,
    'broadcast-message-cancel': 31,
    'script-message': 32,
    'script-message-cancel': 33,
    'unknown-command': 34,
    'thunder-change': 35,
    'thunder-change-cancel': 36,
    'weather-change': 37,
    'weather-change-cancel': 38,
    'dimension-load': 39,
    'map-initialize': 40,
    'plugin-lifecycle': 41,
    'chunk-load': 42,
    'chunk-unload': 43,
    'player-connect': 44,
    'player-login-cancel': 45,
    'player-skin-change-cancel': 46,
    'server-list-ping': 47,
    'server-list-ping-cancel': 48,
    'packet-receive': 49,
    'packet-receive-cancel': 50,
    'packet-send': 51,
    'packet-send-cancel': 52,
    'player-move': 53,
    'player-move-cancel': 54,
    'player-pickup-arrow': 55,
    'player-pickup-arrow-cancel': 56,
    'player-set-spawn': 57,
    'player-set-spawn-cancel': 58,
    'actor-spawn': 59,
    'actor-spawn-cancel': 60,
    'actor-teleport': 61,
    'actor-teleport-cancel': 62,
    'actor-remove': 63,
    'player-hide-actor': 64,
    'player-show-actor': 65,
    'player-bed-enter-leave': 66,
    'player-bed-enter-cancel': 67,
    'actor-damage': 68,
    'actor-damage-cancel': 69,
    'block-from-to': 70,
    'block-from-to-cancel': 71,
    'actor-death': 72,
    'actor-effect': 73,
    'actor-effect-cancel': 74,
    'actor-pickup-item': 75,
    'actor-pickup-item-cancel': 76,
    'actor-collision': 77,
    'actor-collision-cancel': 78,
    'actor-dismount': 79,
    'actor-dismount-cancel': 80,
    'block-piston-cycle': 81,
    'block-piston-extend-cancel': 82,
    'block-piston-retract-cancel': 83,
    'block-form': 84,
    'block-form-cancel': 85,
    'block-grow': 86,
    'block-grow-cancel': 87,
    'leaves-decay': 88,
    'leaves-decay-cancel': 89,
    'block-cook': 90,
    'block-cook-cancel': 91,
    'player-chat': 92,
    'player-chat-cancel': 93,
    'player-command': 94,
    'player-command-cancel': 95,
    'player-arm-swing': 96,
    'player-arm-swing-cancel': 97,
    'player-input': 98,
    'player-jump': 99,
    'player-jump-cancel': 100,
    'player-open-sign': 101,
    'player-open-sign-cancel': 102,
    'player-interact-actor': 103,
    'player-interact-actor-cancel': 104,
    'player-toggle-sneak-start': 105,
    'player-toggle-sneak-stop': 106,
    'player-toggle-sprint-start': 107,
    'player-toggle-sprint-stop': 108,
    'actor-toggle-swim': 109,
    'actor-toggle-glide': 110,
    'player-toggle-crawl': 111,
    'player-recipe-book': 112,
    'player-craft-item': 113,
    'player-craft-item-cancel': 114,
    'player-edit-book': 115,
    'player-edit-book-cancel': 116,
    'player-emote': 117,
    'player-emote-cancel': 118,
    'player-item-held': 119,
    'player-item-held-cancel': 120,
    'player-drop-item': 121,
    'player-drop-item-cancel': 122,
    'player-exp-change': 123,
    'player-level-change': 124,
    'player-pickup-item': 125,
    'player-pickup-item-cancel': 126,
    'player-pickup-experience': 127,
    'player-pickup-experience-cancel': 128,
    'player-riptide': 129,
    'player-death-respawn': 130,
    'player-teleport': 131,
    'player-teleport-cancel': 132,
    'player-dimension-change': 133,
    'player-game-mode-change': 134,
    'player-game-mode-change-cancel': 135,
    'player-toggle-flight-start': 136,
    'player-toggle-flight-stop': 137,
    'player-kick-cancel': 138,
    'player-kick-quit': 139,
}


def build_scenario_groups(ctx, namespace):
    scenarios = [
        *build_gametest_scenarios(ctx, namespace),
        *build_server_scenarios(ctx, namespace),
        *build_player_scenarios(ctx, namespace),
        *build_actor_scenarios(ctx, namespace),
        *build_block_scenarios(ctx, namespace),
    ]
    return sorted(scenarios, key=lambda scenario: _SCENARIO_ORDER[scenario.name])
