"""
Classes relating to the effects that can be applied to entities.
"""

__all__ = ["EffectType"]

class EffectType:
    """
    All effect types.
    """

    SPEED = "minecraft:speed"
    SLOWNESS = "minecraft:slowness"
    HASTE = "minecraft:haste"
    MINING_FATIGUE = "minecraft:mining_fatigue"
    STRENGTH = "minecraft:strength"
    INSTANT_HEALTH = "minecraft:instant_health"
    INSTANT_DAMAGE = "minecraft:instant_damage"
    JUMP_BOOST = "minecraft:jump_boost"
    NAUSEA = "minecraft:nausea"
    REGENERATION = "minecraft:regeneration"
    RESISTANCE = "minecraft:resistance"
    FIRE_RESISTANCE = "minecraft:fire_resistance"
    WATER_BREATHING = "minecraft:water_breathing"
    INVISIBILITY = "minecraft:invisibility"
    BLINDNESS = "minecraft:blindness"
    NIGHT_VISION = "minecraft:night_vision"
    HUNGER = "minecraft:hunger"
    WEAKNESS = "minecraft:weakness"
    POISON = "minecraft:poison"
    WITHER = "minecraft:wither"
    HEALTH_BOOST = "minecraft:health_boost"
    ABSORPTION = "minecraft:absorption"
    SATURATION = "minecraft:saturation"
    LEVITATION = "minecraft:levitation"
    FATAL_POISON = "minecraft:fatal_poison"
    CONDUIT_POWER = "minecraft:conduit_power"
    SLOW_FALLING = "minecraft:slow_falling"
    BAD_OMEN = "minecraft:bad_omen"
    HERO_OF_THE_VILLAGE = "minecraft:hero_of_the_village"
    DARKNESS = "minecraft:darkness"
    TRIAL_OMEN = "minecraft:trial_omen"
    WIND_CHARGED = "minecraft:wind_charged"
    WEAVING = "minecraft:weaving"
    OOZING = "minecraft:oozing"
    INFESTED = "minecraft:infested"
    RAID_OMEN = "minecraft:raid_omen"
    BREATH_OF_THE_NAUTILUS = "minecraft:breath_of_the_nautilus"
